CREATE TABLE "creator_sites" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "business_id" uuid NOT NULL UNIQUE REFERENCES "businesses"("id") ON DELETE cascade, "owner_user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE restrict, "public_id" text NOT NULL UNIQUE, "slug" text NOT NULL UNIQUE, "name" text NOT NULL, "tagline" text NOT NULL DEFAULT '', "bio" text NOT NULL DEFAULT '', "avatar_asset_id" uuid REFERENCES "assets"("id") ON DELETE set null, "theme" json NOT NULL, "seo" json NOT NULL, "status" text NOT NULL DEFAULT 'draft', "revision" integer NOT NULL DEFAULT 1, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "creator_sites_status_check" CHECK ("status" IN ('draft','published','paused','archived')), CONSTRAINT "creator_sites_slug_check" CHECK ("slug" ~ '^[a-z0-9][a-z0-9-]{2,62}$')
);
CREATE TABLE "creator_site_sections" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "site_id" uuid NOT NULL REFERENCES "creator_sites"("id") ON DELETE cascade, "name" text NOT NULL, "kind" text NOT NULL, "payload" json NOT NULL, "sort_order" integer NOT NULL DEFAULT 0, "visibility" text NOT NULL DEFAULT 'public', "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "creator_site_sections_site_order_unique" UNIQUE ("site_id", "sort_order"), CONSTRAINT "creator_site_sections_visibility_check" CHECK ("visibility" IN ('public','members','hidden'))
);
CREATE INDEX "creator_site_sections_site_order_idx" ON "creator_site_sections" ("site_id", "sort_order");
CREATE TABLE "creator_site_redirects" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "site_id" uuid NOT NULL REFERENCES "creator_sites"("id") ON DELETE cascade, "source_path" text NOT NULL, "target_url" text NOT NULL, "status_code" integer NOT NULL DEFAULT 302, "hits" integer NOT NULL DEFAULT 0, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "creator_site_redirects_site_source_unique" UNIQUE ("site_id", "source_path"), CONSTRAINT "creator_site_redirects_status_check" CHECK ("status_code" IN (301,302,307,308))
);
CREATE TABLE "creator_site_domains" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "site_id" uuid NOT NULL REFERENCES "creator_sites"("id") ON DELETE cascade, "domain" text NOT NULL UNIQUE, "verification_token_hash" text NOT NULL, "verification_token_hint" text NOT NULL, "status" text NOT NULL DEFAULT 'pending', "verified_at" timestamp, "last_checked_at" timestamp, "error_code" text, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "creator_site_domains_status_check" CHECK ("status" IN ('pending','verified','active','failed','disconnected'))
);
CREATE INDEX "creator_site_domains_site_status_idx" ON "creator_site_domains" ("site_id", "status");
ALTER TABLE "analytics_events" DROP CONSTRAINT "analytics_events_name_check";
ALTER TABLE "analytics_events" ADD CONSTRAINT "analytics_events_name_check" CHECK ("event_name" IN ('content.exposed','content.engaged','media.played','relationship.started','funnel.step','product.viewed','checkout.started','purchase.completed','entitlement.activated','refund.completed','revenue.allocated','experiment.exposed','podcast.start','podcast.progress','podcast.complete','site.view','site.click','site.subscribe'));
