import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, BarChart3, Clock3, DollarSign, Eye, Loader2, PlayCircle, ShoppingBag } from "lucide-react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { apiRequest } from "@/lib/queryClient";

type Overview = { periodDays: number; metrics: { reach: number; playbackSessions: number; watchMs: number; rebufferRatio: number; conversions: number; revenueCents: number; attributedConversions: number; attributedRevenueCents: number }; events: Record<string, number>; topPosts: Array<{ postId: number; views: number }> };
function Metric({ icon: Icon, label, value, detail }: { icon: typeof Eye; label: string; value: string; detail: string }) { return <article data-testid={`analytics-${label.toLowerCase()}`} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><Icon className="h-5 w-5 text-[#1d9bf0]"/><p className="mt-3 text-[10px] font-black uppercase tracking-widest text-zinc-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p><p className="mt-1 text-[10px] text-zinc-600">{detail}</p></article>; }
function duration(ms: number) { const hours = Math.floor(ms / 3_600_000); const minutes = Math.round((ms % 3_600_000) / 60_000); return hours ? `${hours}h ${minutes}m` : `${minutes}m`; }

export default function AnalyticsOverviewPage() {
  const [, setLocation] = useLocation(); const [days, setDays] = useState(30);
  const query = useQuery<Overview>({ queryKey: ["/api/analytics/overview", days], queryFn: async () => (await apiRequest("GET", `/api/analytics/overview?days=${days}`)).json() });
  const data = query.data;
  return <main className="min-h-[calc(100dvh-3.5rem)] bg-black pb-24 text-white"><header className="sticky top-0 z-20 border-b border-zinc-800 bg-black/95"><div className="mx-auto flex h-14 max-w-5xl items-center gap-3 px-4"><Button size="icon" variant="ghost" onClick={() => setLocation("/business")} aria-label="Back to business"><ArrowLeft className="h-5 w-5"/></Button><div className="flex-1"><h1 className="font-black">Creator intelligence</h1><p className="text-[10px] text-zinc-500">Content → attention → conversion → revenue</p></div><select aria-label="Analytics period" value={days} onChange={(event) => setDays(Number(event.target.value))} className="h-9 rounded-lg border border-zinc-800 bg-zinc-950 px-2 text-xs"><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option><option value={365}>1 year</option></select></div></header>
    <div className="mx-auto max-w-5xl p-4">{query.isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#1d9bf0]"/></div> : <><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={Eye} label="Reach" value={(data?.metrics.reach ?? 0).toLocaleString()} detail="Unique authenticated content exposures"/><Metric icon={PlayCircle} label="Playback" value={(data?.metrics.playbackSessions ?? 0).toLocaleString()} detail={`${duration(data?.metrics.watchMs ?? 0)} watched · ${((data?.metrics.rebufferRatio ?? 0) * 100).toFixed(1)}% buffering`}/><Metric icon={ShoppingBag} label="Conversions" value={(data?.metrics.conversions ?? 0).toLocaleString()} detail={`${data?.metrics.attributedConversions ?? 0} with a trusted touch`}/><Metric icon={DollarSign} label="Revenue" value={`$${((data?.metrics.revenueCents ?? 0) / 100).toLocaleString(undefined, { maximumFractionDigits: 0 })}`} detail={`$${((data?.metrics.attributedRevenueCents ?? 0) / 100).toFixed(0)} attributed`}/></section>
      <section className="mt-5 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><div className="flex items-center gap-2"><BarChart3 className="h-4 w-4 text-[#1d9bf0]"/><h2 className="text-sm font-black">First-party event funnel</h2></div><div className="mt-4 space-y-2">{[["Content exposed", "content.exposed"], ["Content engaged", "content.engaged"], ["Product viewed", "product.viewed"], ["Checkout started", "checkout.started"], ["Purchase completed", "purchase.completed"]].map(([label, key]) => <div key={key} className="flex items-center rounded-xl bg-black px-3 py-2"><span className="flex-1 text-xs text-zinc-400">{label}</span><strong className="text-sm">{data?.events[key] ?? 0}</strong></div>)}</div></article><article className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#1d9bf0]"/><h2 className="text-sm font-black">Top native content</h2></div><div className="mt-4 space-y-2">{data?.topPosts.length ? data.topPosts.map((post) => <button key={post.postId} onClick={() => setLocation(`/posts/${post.postId}/analytics`)} className="flex w-full items-center rounded-xl bg-black px-3 py-2 text-left"><span className="flex-1 text-xs">Post #{post.postId}</span><strong className="text-xs text-zinc-400">{post.views} views</strong></button>) : <p className="rounded-xl border border-dashed border-zinc-800 p-6 text-center text-xs text-zinc-600">Performance appears as your content is viewed and sold.</p>}</div></article></section></>}</div></main>;
}
