import { useQuery } from "@tanstack/react-query";
import { AppWindow, ArrowRight, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

type AppListing = { id: string; name: string; description: string; homepageUrl: string; privacyUrl: string; termsUrl: string; scopes: string[]; authorizeUrl: string | null };
export default function AppsPage() {
  const { data, isLoading } = useQuery<AppListing[]>({ queryKey: ["/api/apps"], queryFn: async () => { const response = await fetch("/api/apps"); if (!response.ok) throw new Error("Unable to load apps"); return response.json(); } });
  return <main className="min-h-screen bg-black px-4 py-10 text-white"><section className="mx-auto max-w-5xl"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-sky-500/15"><AppWindow className="h-6 w-6 text-sky-400" /></div><h1 className="mt-5 text-4xl font-black tracking-tight">CreativesOS Apps</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">Approved extensions use explicit scopes, revocable installations and audited API boundaries. No app receives your password or unrelated business data.</p>
    {isLoading ? <p className="mt-8 text-zinc-500">Loading approved apps…</p> : !data?.length ? <div className="mt-8 rounded-2xl border border-white/10 bg-zinc-950 p-8 text-center"><ShieldCheck className="mx-auto h-7 w-7 text-zinc-600" /><p className="mt-3 font-bold">No public apps yet</p><p className="mt-1 text-sm text-zinc-500">Apps remain private until platform review is approved.</p></div> : <div className="mt-8 grid gap-4 md:grid-cols-2">{data.map((app) => <article key={app.id} className="rounded-2xl border border-white/10 bg-zinc-950 p-5"><h2 className="text-lg font-bold">{app.name}</h2><p className="mt-2 text-sm leading-6 text-zinc-400">{app.description}</p><div className="mt-4 flex flex-wrap gap-2">{app.scopes.map((scope) => <span key={scope} className="rounded-full bg-white/5 px-2.5 py-1 text-[10px] font-bold text-zinc-400">{scope}</span>)}</div><div className="mt-5 flex items-center justify-between gap-3"><div className="flex gap-3 text-xs text-zinc-500"><a className="hover:text-white" href={app.privacyUrl} target="_blank" rel="noreferrer">Privacy</a><a className="hover:text-white" href={app.termsUrl} target="_blank" rel="noreferrer">Terms</a></div>{app.authorizeUrl && <Button onClick={() => window.location.assign(app.authorizeUrl!)}>Install <ArrowRight className="ml-2 h-4 w-4" /></Button>}</div></article>)}</div>}
  </section></main>;
}
