import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Download, FileText, Globe2, Loader2, Mail, Plus, Send, Upload, Users } from "lucide-react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiRequest, queryClient } from "@/lib/queryClient";

type Form = { id: string; name: string; title: string; publicId: string; status: string };
type Page = { id: string; name: string; headline: string; publicId: string; status: string };
type Issue = { id: string; name: string; subject: string; status: string; sentAt?: string | null };
type Studio = { forms: Form[]; landingPages: Page[]; issues: Issue[]; blocks: unknown[]; sequences: Array<{ id: string; name: string; status: string }>; metrics: { subscribers: number; forms: number; issues: number; sent: number; opened: number; clicked: number } };

export default function AudienceStudioPage() {
  const [, setLocation] = useLocation(); const [tab, setTab] = useState("overview"); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const [formName, setFormName] = useState(""); const [formTitle, setFormTitle] = useState("");
  const [issueName, setIssueName] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState("");
  const [csv, setCsv] = useState("email,name,consent,tags\n");
  const query = useQuery<Studio>({ queryKey: ["/api/audience/studio"] }); const studio = query.data;
  const metrics = useMemo(() => [{ label: "Subscribers", value: studio?.metrics.subscribers ?? 0 }, { label: "Capture forms", value: studio?.metrics.forms ?? 0 }, { label: "Issues", value: studio?.metrics.issues ?? 0 }, { label: "Opens", value: studio?.metrics.opened ?? 0 }], [studio]);
  async function refresh() { await queryClient.invalidateQueries({ queryKey: ["/api/audience/studio"] }); }
  async function act(key: string, work: () => Promise<unknown>, success: string) { setBusy(key); setMessage(""); try { await work(); setMessage(success); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed"); } finally { setBusy(""); } }
  const createForm = () => act("form", async () => { await apiRequest("POST", "/api/audience/forms", { name: formName, title: formTitle, description: "Join my owned audience.", fields: [{ key: "first_name", label: "First name", type: "text", required: false }], tags: ["newsletter"], consentPurpose: "marketing", disclosureVersion: "audience-v1", successMessage: "You are on the list." }); setFormName(""); setFormTitle(""); }, "Capture form created.");
  const createIssue = () => act("issue", async () => { await apiRequest("POST", "/api/audience/newsletters/issues", { name: issueName, subject, previewText: body.slice(0, 120), segmentId: null, content: [{ id: crypto.randomUUID(), type: "text", content: { text: body } }], variants: [], scheduledAt: null }); setIssueName(""); setSubject(""); setBody(""); }, "Newsletter draft created.");
  return <main className="min-h-[calc(100dvh-3.5rem)] bg-black pb-24 text-white"><header className="sticky top-0 z-30 border-b border-zinc-800 bg-black/95"><div className="mx-auto flex h-14 max-w-7xl items-center gap-3 px-4"><Button size="icon" variant="ghost" aria-label="Back to business" onClick={() => setLocation("/business")}><ArrowLeft className="h-5 w-5"/></Button><div className="flex-1"><h1 className="font-black">Audience Studio</h1><p className="text-[10px] text-zinc-500">Capture, publish, nurture, and own the relationship</p></div><Users className="h-5 w-5 text-[#1d9bf0]"/></div><nav className="mx-auto flex max-w-7xl gap-1 overflow-x-auto px-4 pb-2">{["overview","capture","newsletters","automations","import"].map((value) => <button key={value} className={`rounded-full px-3 py-1.5 text-xs font-bold capitalize ${tab === value ? "bg-white text-black" : "text-zinc-500 hover:bg-zinc-900"}`} onClick={() => setTab(value)}>{value}</button>)}</nav></header><div className="mx-auto max-w-7xl p-4">{message && <p className="mb-4 rounded-xl border border-[#1d9bf0]/40 bg-[#1d9bf0]/10 p-3 text-xs text-sky-100">{message}</p>}{query.isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin"/></div> : <>
    {tab === "overview" && <><section className="grid grid-cols-2 gap-3 md:grid-cols-4">{metrics.map((metric) => <article key={metric.label} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-[10px] font-black uppercase tracking-widest text-zinc-500">{metric.label}</p><p className="mt-2 text-3xl font-black">{metric.value}</p></article>)}</section><section className="mt-4 grid gap-3 md:grid-cols-3"><article className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><Globe2 className="h-5 w-5 text-[#1d9bf0]"/><h2 className="mt-3 font-bold">Owned capture</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Published forms and landing pages write into the canonical Relationship Hub with consent evidence.</p></article><article className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><Mail className="h-5 w-5 text-[#1d9bf0]"/><h2 className="mt-3 font-bold">Governed publishing</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Every newsletter resolves consent, suppression, preferences, quiet hours, and deduplication.</p></article><article className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><Users className="h-5 w-5 text-[#1d9bf0]"/><h2 className="mt-3 font-bold">Human handoff</h2><p className="mt-1 text-xs leading-5 text-zinc-500">High-value activity becomes an assigned Relationship Hub task instead of disappearing in a campaign report.</p></article></section></>}
    {tab === "capture" && <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><h2 className="font-bold">New capture form</h2><div className="mt-3 space-y-2"><Input aria-label="Form workspace name" placeholder="Weekly briefing" value={formName} onChange={(event) => setFormName(event.target.value)} className="border-zinc-800 bg-black"/><Input aria-label="Public form title" placeholder="Get the creator briefing" value={formTitle} onChange={(event) => setFormTitle(event.target.value)} className="border-zinc-800 bg-black"/><Button className="w-full bg-[#1d9bf0] text-black" disabled={!formName || !formTitle || busy === "form"} onClick={() => void createForm()}><Plus className="mr-1 h-4 w-4"/>Create form</Button></div></section><section className="space-y-2">{studio?.forms.map((form) => <article key={form.id} className="flex items-center gap-3 rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><FileText className="h-5 w-5 text-zinc-500"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{form.title}</p><p className="text-[10px] uppercase text-zinc-600">{form.status} · {form.publicId}</p></div>{form.status === "published" ? <Button size="sm" variant="outline" onClick={() => window.open(`/subscribe/${form.publicId}`, "_blank")}>Open</Button> : <Button size="sm" disabled={busy === form.id} onClick={() => void act(form.id, () => apiRequest("POST", `/api/audience/forms/${form.id}/publish`), "Form published.")}>Publish</Button>}</article>)}{!studio?.forms.length && <p className="rounded-2xl border border-dashed border-zinc-800 p-8 text-center text-xs text-zinc-600">Create your first owned capture form.</p>}</section></div>}
    {tab === "newsletters" && <div className="grid gap-4 lg:grid-cols-[400px_1fr]"><section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><h2 className="font-bold">Compose newsletter</h2><div className="mt-3 space-y-2"><Input aria-label="Internal issue name" placeholder="August creator briefing" value={issueName} onChange={(event) => setIssueName(event.target.value)} className="border-zinc-800 bg-black"/><Input aria-label="Email subject" placeholder="What creators need this week" value={subject} onChange={(event) => setSubject(event.target.value)} className="border-zinc-800 bg-black"/><textarea aria-label="Newsletter body" className="min-h-40 w-full rounded-xl border border-zinc-800 bg-black p-3 text-sm outline-none focus:border-[#1d9bf0]" placeholder="Write the issue…" value={body} onChange={(event) => setBody(event.target.value)}/><Button className="w-full bg-[#1d9bf0] text-black" disabled={!issueName || !subject || !body || busy === "issue"} onClick={() => void createIssue()}><Plus className="mr-1 h-4 w-4"/>Save draft</Button></div></section><section className="space-y-2">{studio?.issues.map((issue) => <article key={issue.id} className="flex items-center gap-3 rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><Mail className="h-5 w-5 text-zinc-500"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{issue.subject}</p><p className="text-[10px] uppercase text-zinc-600">{issue.status}</p></div>{!['sent','sending'].includes(issue.status) && <Button size="sm" disabled={busy === issue.id} onClick={() => void act(issue.id, () => apiRequest("POST", `/api/audience/newsletters/issues/${issue.id}/send`), "Newsletter passed governed delivery.")}><Send className="mr-1 h-3 w-3"/>Send</Button>}</article>)}{!studio?.issues.length && <p className="rounded-2xl border border-dashed border-zinc-800 p-8 text-center text-xs text-zinc-600">Draft your first owned newsletter.</p>}</section></div>}
    {tab === "automations" && <section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-bold">Lifecycle sequences</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-zinc-500">Sequences support manual, form-submission, segment-entry, and tag-added triggers; delayed steps are deduplicated and governed by live consent at dispatch time.</p><div className="mt-4 space-y-2">{studio?.sequences.map((sequence) => <div key={sequence.id} className="rounded-xl border border-zinc-800 bg-black p-3"><p className="text-sm font-bold">{sequence.name}</p><p className="text-[10px] uppercase text-zinc-600">{sequence.status}</p></div>)}{!studio?.sequences.length && <p className="text-xs text-zinc-600">No sequences yet. The native sequence contract is ready for authoring.</p>}</div></section>}
    {tab === "import" && <div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><h2 className="font-bold">Import subscribers</h2><p className="mt-1 text-xs text-zinc-500">CSV columns: email, name, consent, tags. Use semicolons between tags.</p><textarea aria-label="Subscriber CSV" className="mt-3 min-h-64 w-full rounded-xl border border-zinc-800 bg-black p-3 font-mono text-xs" value={csv} onChange={(event) => setCsv(event.target.value)}/><Button className="mt-3 w-full" disabled={busy === "import"} onClick={() => void act("import", () => apiRequest("POST", "/api/audience/import", { csv }), "Import completed with row-level validation.")}><Upload className="mr-1 h-4 w-4"/>Import CSV</Button></section><section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><h2 className="font-bold">Portable audience data</h2><p className="mt-2 text-xs leading-5 text-zinc-500">Exports are tenant-scoped and spreadsheet-formula-safe. Subscriber identity remains in Relationship Hub, not in a newsletter silo.</p><Button className="mt-4" variant="outline" onClick={() => window.location.assign("/api/audience/export.csv")}><Download className="mr-1 h-4 w-4"/>Export CSV</Button></section></div>}
  </>}</div></main>;
}
