import { useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, BadgeDollarSign, CheckCircle2, ClipboardCopy, FileSignature, Handshake, Plus, Send, Target } from "lucide-react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiRequest, queryClient } from "@/lib/queryClient";

type Deal = { id: string; brandName: string; title: string; description: string; currency: string; proposedValueCents: number; contractedValueCents: number; stage: string; disclosure: string };
type Studio = { deals: Deal[]; mediaKits: Array<{ id: string; name: string; headline: string }>; rateCards: Array<{ id: string; name: string; currency: string }>; pipeline: Array<{ stage: string; count: number; valueCents: number }> };
type Detail = { deal: Deal; proposals: Array<{ id: string; status: string; valueCents: number; version: number }>; contract: null | { status: string; creatorSignedName: string | null; brandSignedName: string | null }; milestones: Array<{ id: string; name: string; status: string; amountCents: number }>; invoices: Array<{ id: string; invoiceNumber: string; status: string; amountCents: number }>; performance: Array<{ id: string; metrics: Record<string, number> }> };
const rights = { channels: ["youtube", "instagram", "tiktok"], territories: ["worldwide"], durationDays: 90, paidMedia: false, whitelisting: false, exclusivityCategory: null, exclusivityDays: 0 };
const money = (cents = 0, currency = "usd") => new Intl.NumberFormat(undefined, { style: "currency", currency: currency.toUpperCase(), maximumFractionDigits: 0 }).format(cents / 100);

export default function SponsorshipStudioPage() {
  const [, setLocation] = useLocation(); const [selectedId, setSelectedId] = useState(""); const [brandName, setBrandName] = useState(""); const [title, setTitle] = useState(""); const [value, setValue] = useState("2500"); const [message, setMessage] = useState("");
  const studio = useQuery<Studio>({ queryKey: ["/api/sponsorship"] }); const detail = useQuery<Detail>({ queryKey: [`/api/sponsorship/deals/${selectedId}`], enabled: Boolean(selectedId) });
  const selected = detail.data; const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["/api/sponsorship"] }), selectedId ? queryClient.invalidateQueries({ queryKey: [`/api/sponsorship/deals/${selectedId}`] }) : Promise.resolve()]); };
  const act = useMutation({ mutationFn: async ({ method = "POST", path, body }: { method?: "POST" | "PATCH"; path: string; body?: unknown }) => { const response = await apiRequest(method, path, body); return response.json(); }, onSuccess: async () => { setMessage("Saved."); await refresh(); }, onError: (error) => setMessage(error instanceof Error ? error.message : "Action failed") });
  const totalPipeline = useMemo(() => studio.data?.pipeline.reduce((sum, item) => sum + item.valueCents, 0) ?? 0, [studio.data]);
  async function createDeal() { const response = await apiRequest("POST", "/api/sponsorship/deals", { brandName, contactId: null, campaignId: null, title, description: "Creator partnership campaign", currency: "usd", proposedValueCents: Math.round(Number(value) * 100), disclosure: "#ad", usageRights: rights, renewalAt: null }); const deal = await response.json() as Deal; setBrandName(""); setTitle(""); setSelectedId(deal.id); await refresh(); }
  async function createPortal() { if (!selected) return; const response = await apiRequest("POST", `/api/sponsorship/deals/${selected.deal.id}/portal`, { stakeholderName: `${selected.deal.brandName} reviewer`, stakeholderEmail: `review+${selected.deal.id.slice(0, 8)}@example.com` }); const payload = await response.json() as { portalUrl: string }; await navigator.clipboard?.writeText(payload.portalUrl); setMessage(`Brand portal copied: ${payload.portalUrl}`); await refresh(); }
  return <main className="min-h-dvh bg-black pb-24 text-white"><header className="border-b border-zinc-800"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4"><Button variant="ghost" size="icon" onClick={() => setLocation("/business")} aria-label="Back to business"><ArrowLeft/></Button><Handshake className="text-[#1d9bf0]"/><div><h1 className="font-black">Sponsorship Studio</h1><p className="text-[10px] text-zinc-500">Proof, pricing, negotiation, contracts, delivery, invoicing, and renewals</p></div></div></header><div className="mx-auto max-w-7xl p-4">
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><article className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-[10px] font-black uppercase text-zinc-500">Pipeline</p><strong className="mt-2 block text-2xl">{money(totalPipeline)}</strong></article>{studio.data?.pipeline.filter((item) => item.count).slice(0,3).map((item) => <article key={item.stage} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-[10px] font-black uppercase text-zinc-500">{item.stage}</p><strong className="mt-2 block text-2xl">{item.count}</strong><span className="text-xs text-zinc-600">{money(item.valueCents)}</span></article>)}</section>
    <div className="mt-5 grid gap-5 lg:grid-cols-[340px_1fr]"><aside className="space-y-4"><section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><h2 className="font-bold">New opportunity</h2><Input aria-label="Brand name" placeholder="Brand name" className="mt-3 border-zinc-800 bg-black" value={brandName} onChange={(e) => setBrandName(e.target.value)}/><Input aria-label="Campaign title" placeholder="Campaign title" className="mt-2 border-zinc-800 bg-black" value={title} onChange={(e) => setTitle(e.target.value)}/><Input aria-label="Proposed value" type="number" placeholder="2500" className="mt-2 border-zinc-800 bg-black" value={value} onChange={(e) => setValue(e.target.value)}/><Button className="mt-3 w-full bg-[#1d9bf0] text-black" disabled={!brandName || !title || act.isPending} onClick={() => void createDeal()}><Plus className="mr-1 h-4 w-4"/>Create deal</Button></section><section className="rounded-2xl border border-zinc-800 bg-zinc-950 p-3"><h2 className="px-2 pb-2 text-xs font-black uppercase text-zinc-500">Pipeline</h2>{studio.data?.deals.map((deal) => <button key={deal.id} onClick={() => setSelectedId(deal.id)} className={`mb-1 w-full rounded-xl border p-3 text-left ${selectedId === deal.id ? "border-[#1d9bf0] bg-[#1d9bf0]/10" : "border-transparent bg-black hover:border-zinc-700"}`}><strong className="block text-sm">{deal.brandName}</strong><span className="block truncate text-xs text-zinc-500">{deal.title}</span><span className="mt-1 block text-[10px] uppercase text-zinc-600">{deal.stage} · {money(deal.contractedValueCents || deal.proposedValueCents, deal.currency)}</span></button>)}</section></aside>
      <section className="min-w-0 rounded-2xl border border-zinc-800 bg-zinc-950 p-4">{!selected ? <div className="grid min-h-[420px] place-items-center text-center text-zinc-600"><div><Handshake className="mx-auto h-10 w-10"/><p className="mt-3 text-sm">Select a deal to operate its complete lifecycle.</p></div></div> : <div><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-[#1d9bf0]">{selected.deal.stage}</p><h2 className="text-2xl font-black">{selected.deal.title}</h2><p className="text-sm text-zinc-500">{selected.deal.brandName} · {money(selected.deal.contractedValueCents || selected.deal.proposedValueCents, selected.deal.currency)}</p></div><Button variant="outline" onClick={() => void createPortal()}><ClipboardCopy className="mr-2 h-4 w-4"/>Copy brand portal</Button></div>{message && <p role="status" className="mt-3 rounded-xl border border-[#1d9bf0]/20 bg-[#1d9bf0]/10 p-3 text-xs">{message}</p>}
        <div className="mt-5 grid gap-3 md:grid-cols-2"><Lifecycle title="Proposal" icon={Send} state={selected.proposals[0]?.status ?? "not created"}><Button size="sm" disabled={Boolean(selected.proposals.length) || act.isPending} onClick={() => act.mutate({ path: `/api/sponsorship/deals/${selected.deal.id}/proposals`, body: { summary: "Integrated creator partnership with measurable distribution and reporting.", valueCents: selected.deal.proposedValueCents, validUntil: new Date(Date.now()+7*86400000).toISOString(), deliverables: [{ id: "integrated-video", title: "Integrated campaign content", channel: "youtube", quantity: 1, dueAt: null, requirements: "Approved brief and disclosure", distributionJobId: null }], paymentTerms: "Net 30 after approved milestone", cancellationTerms: "Completed work remains payable", usageRights: rights } })}>Create proposal</Button></Lifecycle>
          <Lifecycle title="Contract" icon={FileSignature} state={selected.contract?.status ?? "awaiting acceptance"}><Button size="sm" disabled={!selected.contract || Boolean(selected.contract.creatorSignedName) || act.isPending} onClick={() => act.mutate({ path: `/api/sponsorship/deals/${selected.deal.id}/sign`, body: { name: "Creator owner" } })}>Creator sign</Button></Lifecycle>
          <Lifecycle title="Delivery" icon={Target} state={selected.milestones[0]?.status ?? "not planned"}><Button size="sm" disabled={Boolean(selected.milestones.length) || act.isPending} onClick={() => act.mutate({ path: `/api/sponsorship/deals/${selected.deal.id}/milestones`, body: { name: "Campaign delivery", description: "Brand-approved deliverables", dueAt: null, amountCents: selected.deal.contractedValueCents || selected.deal.proposedValueCents } })}>Add milestone</Button>{selected.milestones[0] && <Button size="sm" variant="outline" disabled={selected.milestones[0].status === "approved" || act.isPending} onClick={() => act.mutate({ method: "PATCH", path: `/api/sponsorship/milestones/${selected.milestones[0].id}`, body: { status: "approved" } })}>Approve</Button>}</Lifecycle>
          <Lifecycle title="Invoice" icon={BadgeDollarSign} state={selected.invoices[0]?.status ?? "not issued"}><Button size="sm" disabled={!selected.milestones.find((item) => item.status === "approved") || Boolean(selected.invoices.length) || act.isPending} onClick={() => { const milestone = selected.milestones.find((item) => item.status === "approved")!; act.mutate({ path: `/api/sponsorship/deals/${selected.deal.id}/invoices`, body: { milestoneId: milestone.id, dueAt: new Date(Date.now()+30*86400000).toISOString() } }); }}>Create invoice</Button>{selected.invoices[0] && <span className="text-xs text-zinc-500">{selected.invoices[0].invoiceNumber} · {money(selected.invoices[0].amountCents)}</span>}</Lifecycle></div>
        <section className="mt-4 rounded-xl border border-zinc-800 bg-black p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold">Performance & renewal proof</h3><p className="text-xs text-zinc-600">Capture outcomes now; provider attribution can enrich the same record later.</p></div><Button variant="outline" size="sm" disabled={act.isPending} onClick={() => act.mutate({ path: `/api/sponsorship/deals/${selected.deal.id}/performance`, body: { source: "manual", metrics: { impressions: 10000, clicks: 500, conversions: 25 } } })}><CheckCircle2 className="mr-1 h-4 w-4"/>Add snapshot</Button></div>{selected.performance[0] && <div className="mt-3 flex flex-wrap gap-2">{Object.entries(selected.performance[0].metrics).map(([key, value]) => <span key={key} className="rounded-full bg-zinc-900 px-3 py-1 text-xs">{key}: {value.toLocaleString()}</span>)}</div>}</section>
      </div>}</section></div></div></main>;
}
function Lifecycle({ title, icon: Icon, state, children }: { title: string; icon: typeof Handshake; state: string; children: React.ReactNode }) { return <article className="rounded-xl border border-zinc-800 bg-black p-4"><div className="flex items-start gap-3"><Icon className="mt-0.5 h-5 w-5 text-[#1d9bf0]"/><div className="min-w-0 flex-1"><h3 className="text-sm font-bold">{title}</h3><p className="text-[10px] uppercase text-zinc-600">{state}</p><div className="mt-3 flex flex-wrap items-center gap-2">{children}</div></div></div></article>; }
