import { createHash, randomBytes } from "node:crypto";
import type { Express, NextFunction, Request, Response } from "express";
import { and, count, desc, eq, gt, inArray, lt, sql } from "drizzle-orm";
import { affiliateApplicationSchema, calculateAffiliateCommission, createAffiliateProgramSchema } from "@shared/affiliate";
import { affiliateApplications, affiliateClicks, affiliateConversions, affiliateFraudSignals, affiliateLedgerEntries, affiliateLinks, affiliatePartners, affiliatePayouts, affiliatePrograms, orderItems, orders, products } from "@shared/schema";
import { attachUser } from "./auth";
import { ensureDefaultBusiness, userCanManageBusiness } from "./businesses";
import { db } from "./db";

type Handler = (req: Request, res: Response, next: NextFunction) => unknown;
const safe = (handler: Handler): Handler => (req,res,next) => { try { Promise.resolve(handler(req,res,next)).catch(next); } catch (error) { next(error); } };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const cookie = (req: Request, name: string) => (req.headers.cookie ?? "").split(";").map((part) => part.trim()).find((part) => part.startsWith(`${name}=`))?.slice(name.length + 1) ?? null;
const safeDestination = (raw: string) => { const base = new URL((process.env.PUBLIC_APP_URL ?? "https://creativesos.net").replace(/\/$/, "")); const url = new URL(raw, base); if (!['http:','https:'].includes(url.protocol)) throw new Error("Unsupported destination URL"); return url.toString(); };
const code = (prefix: string) => `${prefix.replace(/[^a-z0-9]/gi, "").slice(0, 10).toUpperCase()}${randomBytes(4).toString("hex").toUpperCase()}`;
async function ownedProgram(userId: number, programId: string) { const [program] = await db.select().from(affiliatePrograms).where(eq(affiliatePrograms.id, programId)).limit(1); return program && await userCanManageBusiness(userId, program.businessId) ? program : null; }

export async function affiliateAttributionForCheckout(req: Request, buyerUserId: number, productIds: number[]) {
  const clickToken = cookie(req, "cos_ref"); if (!clickToken) return null;
  const [row] = await db.select({ click: affiliateClicks, partner: affiliatePartners, program: affiliatePrograms }).from(affiliateClicks).innerJoin(affiliatePartners, eq(affiliateClicks.partnerId, affiliatePartners.id)).innerJoin(affiliatePrograms, eq(affiliateClicks.programId, affiliatePrograms.id)).where(and(eq(affiliateClicks.clickToken, clickToken), gt(affiliateClicks.expiresAt, new Date()), eq(affiliatePartners.status, "active"), eq(affiliatePrograms.status, "active"))).limit(1);
  if (!row || (row.program.productIds.length && !productIds.some((id) => row.program.productIds.includes(id)))) return null;
  const selfReferral = row.partner.userId === buyerUserId;
  if (selfReferral) await db.insert(affiliateFraudSignals).values({ programId: row.program.id, partnerId: row.partner.id, clickId: row.click.id, signal: "self_referral", severity: "high", evidence: { buyerUserId } });
  return { affiliateClickId: row.click.id, affiliateProgramId: row.program.id, affiliatePartnerId: row.partner.id, affiliateModel: row.program.attributionModel, affiliateSelfReferral: selfReferral };
}

export async function recordAffiliateOrderConversion(input: { orderId: string; sourceReference?: string; cycleIndex?: number; grossRevenueCents?: number }) {
  const [order] = await db.select().from(orders).where(eq(orders.id, input.orderId)).limit(1); if (!order) throw new Error("Order not found");
  const clickId = typeof order.attributionContext?.affiliateClickId === "string" ? order.attributionContext.affiliateClickId : null; if (!clickId) return null;
  const [row] = await db.select({ click: affiliateClicks, partner: affiliatePartners, program: affiliatePrograms }).from(affiliateClicks).innerJoin(affiliatePartners, eq(affiliateClicks.partnerId, affiliatePartners.id)).innerJoin(affiliatePrograms, eq(affiliateClicks.programId, affiliatePrograms.id)).where(eq(affiliateClicks.id, clickId)).limit(1); if (!row) return null;
  const items = await db.select({ productId: orderItems.productId }).from(orderItems).where(eq(orderItems.orderId, order.id)); if (row.program.productIds.length && !items.some((item) => row.program.productIds.includes(item.productId))) return null;
  const sourceReference = input.sourceReference ?? `order:${order.id}`; const cycleIndex = input.cycleIndex ?? 0; if (cycleIndex > 0 && row.program.commissionRule.recurringCycles > 0 && cycleIndex > row.program.commissionRule.recurringCycles) return null;
  const gross = input.grossRevenueCents ?? Math.max(0, Math.round((order.totalAmount - order.refundedAmount) * 100)); const riskReasons = [...row.click.riskReasons]; let riskScore = row.click.riskScore;
  if (row.partner.userId === order.buyerId || order.attributionContext?.affiliateSelfReferral === true) { riskReasons.push("self_referral"); riskScore = Math.max(riskScore, 100); }
  if (row.program.commissionRule.newCustomersOnly) { const [prior] = await db.select({ value: count() }).from(orders).where(and(eq(orders.buyerId, order.buyerId), inArray(orders.financialStatus, ["paid","partially_refunded","dispute_won"]), lt(orders.createdAt, order.createdAt))); if (Number(prior.value) > 0) { riskReasons.push("not_new_customer"); riskScore = Math.max(riskScore, 100); } }
  const qualified = riskScore >= 70 ? 0 : gross; const commission = calculateAffiliateCommission(qualified, row.program.commissionRule); const holdUntil = new Date(Date.now() + row.program.holdDays * 86400000);
  return db.transaction(async (tx) => { const [conversion] = await tx.insert(affiliateConversions).values({ programId: row.program.id, partnerId: row.partner.id, clickId: row.click.id, orderId: order.id, buyerUserId: order.buyerId, sourceReference, cycleIndex, grossRevenueCents: gross, qualifiedRevenueCents: qualified, commissionCents: commission, currency: order.currency, status: riskScore >= 70 ? "rejected" : "pending", riskScore, riskReasons, holdUntil }).onConflictDoNothing().returning(); if (!conversion) return null; if (commission > 0) await tx.insert(affiliateLedgerEntries).values({ programId: row.program.id, partnerId: row.partner.id, conversionId: conversion.id, kind: "commission", amountCents: commission, currency: order.currency, sourceReference: `commission:${conversion.id}`, status: "pending", availableAt: holdUntil }); if (riskScore >= 70) await tx.insert(affiliateFraudSignals).values({ programId: row.program.id, partnerId: row.partner.id, clickId: row.click.id, conversionId: conversion.id, signal: riskReasons[0] ?? "high_risk_conversion", severity: "high", evidence: { riskScore, riskReasons } }); return conversion; });
}

export async function reverseAffiliateOrderCommission(input: { orderId: string; affectedAmountCents: number; sourceReference: string; reason: string }) { const conversions = await db.select().from(affiliateConversions).where(eq(affiliateConversions.orderId, input.orderId)); for (const conversion of conversions) { const target = Math.min(conversion.commissionCents, Math.floor(conversion.commissionCents * Math.min(conversion.grossRevenueCents, input.affectedAmountCents) / Math.max(1, conversion.grossRevenueCents))); const delta = Math.max(0, target - conversion.reversedCents); if (!delta) continue; await db.transaction(async (tx) => { await tx.update(affiliateConversions).set({ reversedCents: conversion.reversedCents + delta, status: conversion.reversedCents + delta >= conversion.commissionCents ? "reversed" : "partially_reversed", updatedAt: new Date() }).where(eq(affiliateConversions.id, conversion.id)); await tx.insert(affiliateLedgerEntries).values({ programId: conversion.programId, partnerId: conversion.partnerId, conversionId: conversion.id, kind: "reversal", amountCents: -delta, currency: conversion.currency, sourceReference: `reversal:${input.sourceReference}:${conversion.id}`, status: "available", availableAt: new Date() }).onConflictDoNothing(); }); } }

export function registerAffiliateRoutes(base: Express) {
  const app = { get: (path: string,...handlers: Handler[]) => base.get(path,...handlers.map(safe)), post: (path: string,...handlers: Handler[]) => base.post(path,...handlers.map(safe)), patch: (path: string,...handlers: Handler[]) => base.patch(path,...handlers.map(safe)) };
  app.get("/api/affiliates", attachUser, async (req,res) => { const business = await ensureDefaultBusiness(req.dbUser!); const programs = await db.select().from(affiliatePrograms).where(eq(affiliatePrograms.businessId, business.id)).orderBy(desc(affiliatePrograms.updatedAt)); const ids = programs.map((item) => item.id); if (!ids.length) return res.json({ programs: [], applications: [], partners: [], conversions: [], payouts: [], leaderboard: [] }); const [applications, partners, conversions, payouts] = await Promise.all([db.select().from(affiliateApplications).where(inArray(affiliateApplications.programId, ids)).orderBy(desc(affiliateApplications.createdAt)), db.select().from(affiliatePartners).where(inArray(affiliatePartners.programId, ids)).orderBy(desc(affiliatePartners.joinedAt)), db.select().from(affiliateConversions).where(inArray(affiliateConversions.programId, ids)).orderBy(desc(affiliateConversions.createdAt)), db.select().from(affiliatePayouts).where(inArray(affiliatePayouts.programId, ids)).orderBy(desc(affiliatePayouts.requestedAt))]); const leaderboard = partners.map((partner) => { const rows = conversions.filter((item) => item.partnerId === partner.id); return { partner, conversions: rows.length, revenueCents: rows.reduce((sum,item) => sum + item.qualifiedRevenueCents,0), commissionCents: rows.reduce((sum,item) => sum + item.commissionCents - item.reversedCents,0) }; }).sort((a,b) => b.commissionCents-a.commissionCents); return res.json({ programs, applications, partners, conversions, payouts, leaderboard }); });
  app.post("/api/affiliates/programs", attachUser, async (req,res) => { const parsed = createAffiliateProgramSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid program" }); const business = await ensureDefaultBusiness(req.dbUser!); if (parsed.data.productIds.length) { const owned = await db.select({ id: products.id }).from(products).where(and(inArray(products.id, parsed.data.productIds), eq(products.userId, req.dbUser!.id))); if (owned.length !== parsed.data.productIds.length) return res.status(404).json({ message: "Every program offer must be owned by this business" }); } const [program] = await db.insert(affiliatePrograms).values({ businessId: business.id, ownerUserId: req.dbUser!.id, ...parsed.data }).returning(); return res.status(201).json(program); });
  app.patch("/api/affiliates/programs/:id/status", attachUser, async (req,res) => { const program = await ownedProgram(req.dbUser!.id, req.params.id); const status = String(req.body?.status ?? ""); if (!program) return res.status(404).json({ message: "Program not found" }); if (!['draft','active','paused','archived'].includes(status)) return res.status(400).json({ message: "Invalid status" }); const [updated] = await db.update(affiliatePrograms).set({ status, updatedAt: new Date() }).where(eq(affiliatePrograms.id, program.id)).returning(); return res.json(updated); });
  app.get("/api/public/affiliates/programs/:slug", async (req,res) => { const [program] = await db.select().from(affiliatePrograms).where(and(eq(affiliatePrograms.slug, req.params.slug), eq(affiliatePrograms.status, "active"))).limit(1); if (!program) return res.status(404).json({ message: "Program unavailable" }); return res.json({ id: program.id, name: program.name, slug: program.slug, description: program.description, applicationMode: program.applicationMode, attributionWindowDays: program.attributionWindowDays, commissionRule: program.commissionRule, currency: program.currency }); });
  app.get("/api/public/affiliates/programs/:slug/leaderboard", async (req,res) => { const [program] = await db.select().from(affiliatePrograms).where(and(eq(affiliatePrograms.slug,req.params.slug),eq(affiliatePrograms.status,"active"))).limit(1); if (!program) return res.status(404).json({message:"Program unavailable"}); const rows = await db.select({ partnerId:affiliatePartners.id, displayName:affiliatePartners.displayName, partnerType:affiliatePartners.partnerType, conversions:count(), revenueCents:sql<number>`coalesce(sum(${affiliateConversions.qualifiedRevenueCents}),0)::bigint`, commissionCents:sql<number>`coalesce(sum(${affiliateConversions.commissionCents}-${affiliateConversions.reversedCents}),0)::bigint` }).from(affiliatePartners).leftJoin(affiliateConversions,eq(affiliateConversions.partnerId,affiliatePartners.id)).where(and(eq(affiliatePartners.programId,program.id),eq(affiliatePartners.status,"active"))).groupBy(affiliatePartners.id).orderBy(desc(sql`coalesce(sum(${affiliateConversions.commissionCents}-${affiliateConversions.reversedCents}),0)`)).limit(100); return res.json(rows); });
  app.get("/api/affiliates/me", attachUser, async (req,res) => { const partners = await db.select().from(affiliatePartners).where(eq(affiliatePartners.userId,req.dbUser!.id)); if (!partners.length) return res.json({partners:[],links:[],conversions:[],ledger:[],payouts:[]}); const ids=partners.map((item)=>item.id); const [links,conversions,ledger,payouts]=await Promise.all([db.select().from(affiliateLinks).where(inArray(affiliateLinks.partnerId,ids)),db.select().from(affiliateConversions).where(inArray(affiliateConversions.partnerId,ids)).orderBy(desc(affiliateConversions.createdAt)),db.select().from(affiliateLedgerEntries).where(inArray(affiliateLedgerEntries.partnerId,ids)).orderBy(desc(affiliateLedgerEntries.createdAt)),db.select().from(affiliatePayouts).where(inArray(affiliatePayouts.partnerId,ids)).orderBy(desc(affiliatePayouts.requestedAt))]); return res.json({partners,links,conversions,ledger,payouts}); });
  app.post("/api/affiliates/programs/:id/apply", attachUser, async (req,res) => { const parsed = affiliateApplicationSchema.safeParse(req.body); const [program] = await db.select().from(affiliatePrograms).where(and(eq(affiliatePrograms.id, req.params.id), eq(affiliatePrograms.status, "active"))).limit(1); if (!program) return res.status(404).json({ message: "Program unavailable" }); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid application" }); if (program.applicationMode === "invite_only") return res.status(403).json({ message: "This program is invite only" }); const [application] = await db.insert(affiliateApplications).values({ programId: program.id, applicantUserId: req.dbUser!.id, ...parsed.data, status: program.applicationMode === "open" ? "approved" : "pending" }).onConflictDoNothing().returning(); if (!application) return res.status(409).json({ message: "An application already exists for this email" }); if (application.status === "approved") await db.insert(affiliatePartners).values({ programId: program.id, applicationId: application.id, userId: req.dbUser!.id, displayName: application.displayName, email: application.email, partnerType: application.partnerType, code: code(program.slug) }); return res.status(201).json(application); });
  app.patch("/api/affiliates/applications/:id", attachUser, async (req,res) => { const [application] = await db.select().from(affiliateApplications).where(eq(affiliateApplications.id, req.params.id)).limit(1); const program = application ? await ownedProgram(req.dbUser!.id, application.programId) : null; const status = String(req.body?.status ?? ""); if (!application || !program) return res.status(404).json({ message: "Application not found" }); if (!['approved','declined','waitlisted'].includes(status)) return res.status(400).json({ message: "Invalid decision" }); const [updated] = await db.update(affiliateApplications).set({ status, reviewedByUserId: req.dbUser!.id, reviewNote: typeof req.body?.note === "string" ? req.body.note.slice(0,2000) : "", updatedAt: new Date() }).where(eq(affiliateApplications.id, application.id)).returning(); let partner = null; if (status === "approved") [partner] = await db.insert(affiliatePartners).values({ programId: program.id, applicationId: application.id, userId: application.applicantUserId, displayName: application.displayName, email: application.email, partnerType: application.partnerType, code: code(program.slug) }).onConflictDoNothing().returning(); return res.json({ application: updated, partner }); });
  app.post("/api/affiliates/partners/:id/links", attachUser, async (req,res) => { const [partner] = await db.select().from(affiliatePartners).where(eq(affiliatePartners.id, req.params.id)).limit(1); const program = partner ? await ownedProgram(req.dbUser!.id, partner.programId) : null; if (!partner || !program) return res.status(404).json({ message: "Partner not found" }); const destinationUrl = safeDestination(String(req.body?.destinationUrl ?? "/")); const name = typeof req.body?.name === "string" ? req.body.name.trim().slice(0,160) : ""; if (!name) return res.status(400).json({ message: "Link name is required" }); const [link] = await db.insert(affiliateLinks).values({ partnerId: partner.id, name, destinationUrl, slug: `${partner.code.toLowerCase()}-${randomBytes(3).toString("hex")}` }).returning(); return res.status(201).json({ ...link, referralUrl: `${(process.env.PUBLIC_APP_URL ?? "https://creativesos.net").replace(/\/$/,"")}/r/${link.slug}` }); });
  app.get("/r/:slug", async (req,res) => { const [row] = await db.select({ link: affiliateLinks, partner: affiliatePartners, program: affiliatePrograms }).from(affiliateLinks).innerJoin(affiliatePartners, eq(affiliateLinks.partnerId, affiliatePartners.id)).innerJoin(affiliatePrograms, eq(affiliatePartners.programId, affiliatePrograms.id)).where(and(eq(affiliateLinks.slug, req.params.slug), eq(affiliateLinks.status, "active"), eq(affiliatePartners.status, "active"), eq(affiliatePrograms.status, "active"))).limit(1); if (!row) return res.status(404).send("Referral link unavailable"); const ipHash = hash(`${process.env.AFFILIATE_HASH_SALT ?? "local"}:${req.ip}`); const [recent] = await db.select({ value: count() }).from(affiliateClicks).where(and(eq(affiliateClicks.ipHash, ipHash), gt(affiliateClicks.occurredAt, new Date(Date.now()-3600000)))); const riskReasons = Number(recent.value) >= 50 ? ["high_click_velocity"] : []; const clickToken = randomBytes(24).toString("base64url"); const consentGranted = !row.program.cookieConsentRequired || req.query.consent === "granted"; const [clickRow] = await db.insert(affiliateClicks).values({ programId: row.program.id, partnerId: row.partner.id, linkId: row.link.id, clickToken, anonymousId: typeof req.query.aid === "string" ? req.query.aid.slice(0,128) : null, ipHash, userAgentHash: hash(String(req.get("user-agent") ?? "unknown")), destinationUrl: row.link.destinationUrl, consentState: consentGranted ? "granted" : "essential_only", riskScore: riskReasons.length ? 60 : 0, riskReasons, expiresAt: new Date(Date.now()+row.program.attributionWindowDays*86400000) }).returning(); await db.update(affiliateLinks).set({ clickCount: sql`${affiliateLinks.clickCount} + 1`, updatedAt: new Date() }).where(eq(affiliateLinks.id,row.link.id)); if (riskReasons.length) await db.insert(affiliateFraudSignals).values({ programId: row.program.id, partnerId: row.partner.id, clickId: clickRow.id, signal: "high_click_velocity", severity: "medium", evidence: { hourlyCount: Number(recent.value)+1 } }); if (consentGranted) res.setHeader("Set-Cookie", `cos_ref=${clickToken}; Max-Age=${row.program.attributionWindowDays*86400}; Path=/; HttpOnly; SameSite=Lax${req.secure ? "; Secure" : ""}`); return res.redirect(302, row.link.destinationUrl); });
  app.post("/api/affiliates/programs/:id/conversions", attachUser, async (req,res) => { const program = await ownedProgram(req.dbUser!.id, req.params.id); const partnerId = typeof req.body?.partnerId === "string" ? req.body.partnerId : ""; const gross = Number(req.body?.grossRevenueCents); const sourceReference = typeof req.body?.sourceReference === "string" ? req.body.sourceReference.trim().slice(0,255) : ""; if (!program) return res.status(404).json({ message: "Program not found" }); const [partner] = await db.select().from(affiliatePartners).where(and(eq(affiliatePartners.id, partnerId), eq(affiliatePartners.programId, program.id), eq(affiliatePartners.status,"active"))).limit(1); if (!partner || !Number.isSafeInteger(gross) || gross < 0 || !sourceReference) return res.status(400).json({ message: "Valid partner, revenue, and source reference required" }); const commission = calculateAffiliateCommission(gross, program.commissionRule); const holdUntil = new Date(Date.now()+program.holdDays*86400000); const [conversion] = await db.insert(affiliateConversions).values({ programId: program.id, partnerId: partner.id, sourceReference, grossRevenueCents: gross, qualifiedRevenueCents: gross, commissionCents: commission, currency: program.currency, holdUntil }).onConflictDoNothing().returning(); if (!conversion) return res.status(409).json({ message: "Conversion source already recorded" }); await db.insert(affiliateLedgerEntries).values({ programId: program.id, partnerId: partner.id, conversionId: conversion.id, kind:"commission", amountCents:commission, currency:program.currency, sourceReference:`commission:${conversion.id}`, status:"pending", availableAt:holdUntil }); return res.status(201).json(conversion); });
  app.post("/api/affiliates/programs/:id/reconcile", attachUser, async (req,res) => { const program = await ownedProgram(req.dbUser!.id, req.params.id); if (!program) return res.status(404).json({ message: "Program not found" }); const matured = await db.select().from(affiliateConversions).where(and(eq(affiliateConversions.programId,program.id),eq(affiliateConversions.status,"pending"),lt(affiliateConversions.holdUntil,new Date(Date.now()+1000)))); for (const conversion of matured) await db.transaction(async (tx) => { await tx.update(affiliateConversions).set({ status:"payable",approvedAt:new Date(),updatedAt:new Date() }).where(eq(affiliateConversions.id,conversion.id)); await tx.update(affiliateLedgerEntries).set({ status:"available" }).where(and(eq(affiliateLedgerEntries.conversionId,conversion.id),eq(affiliateLedgerEntries.status,"pending"))); }); return res.json({ matured: matured.length }); });
  app.post("/api/affiliates/conversions/:id/reverse", attachUser, async (req,res) => { const [conversion] = await db.select().from(affiliateConversions).where(eq(affiliateConversions.id,req.params.id)).limit(1); const program = conversion ? await ownedProgram(req.dbUser!.id,conversion.programId) : null; const amount = Number(req.body?.amountCents); const source = typeof req.body?.sourceReference === "string" ? req.body.sourceReference.slice(0,255) : ""; if (!conversion || !program) return res.status(404).json({ message:"Conversion not found" }); if (!Number.isSafeInteger(amount) || amount <= 0 || conversion.reversedCents+amount>conversion.commissionCents || !source) return res.status(400).json({ message:"Valid bounded reversal and source required" }); const [updated] = await db.transaction(async (tx) => { const [row] = await tx.update(affiliateConversions).set({ reversedCents:conversion.reversedCents+amount,status:conversion.reversedCents+amount===conversion.commissionCents?"reversed":"partially_reversed",updatedAt:new Date() }).where(eq(affiliateConversions.id,conversion.id)).returning(); await tx.insert(affiliateLedgerEntries).values({ programId:conversion.programId,partnerId:conversion.partnerId,conversionId:conversion.id,kind:"reversal",amountCents:-amount,currency:conversion.currency,sourceReference:`reversal:${source}`,status:"available",availableAt:new Date() }); return [row]; }); return res.json(updated); });
  app.post("/api/affiliates/partners/:id/payouts", attachUser, async (req,res) => { const [partner] = await db.select().from(affiliatePartners).where(eq(affiliatePartners.id,req.params.id)).limit(1); const program = partner ? await ownedProgram(req.dbUser!.id,partner.programId) : null; if (!partner || !program) return res.status(404).json({ message:"Partner not found" }); const entries = await db.select().from(affiliateLedgerEntries).where(and(eq(affiliateLedgerEntries.partnerId,partner.id),eq(affiliateLedgerEntries.status,"available"))); const balance = entries.reduce((sum,item)=>sum+item.amountCents,0); if (balance < program.minimumPayoutCents) return res.status(409).json({ message:`Minimum payout is ${program.minimumPayoutCents} cents` }); const positive = entries.filter((item)=>item.amountCents>0); const [payout] = await db.transaction(async (tx) => { const [created] = await tx.insert(affiliatePayouts).values({ programId:program.id,partnerId:partner.id,amountCents:balance,currency:program.currency,status:"provider_pending",ledgerEntryIds:entries.map((item)=>item.id) }).returning(); if (positive.length) await tx.update(affiliateLedgerEntries).set({ status:"reserved" }).where(inArray(affiliateLedgerEntries.id,positive.map((item)=>item.id))); return [created]; }); return res.status(201).json({ ...payout, providerStatus:"provider_pending" }); });
}
