import { createHash, randomBytes } from "node:crypto";
import type { Express } from "express";
import { and, asc, desc, eq, gt, inArray, isNull, lte, or, sql } from "drizzle-orm";
import {
  audienceFormSubmissions, audienceForms, audienceLandingPages, audiencePreferenceTokens,
  audienceProfiles, audienceSegmentMemberships, audienceSegments, newsletterBlocks,
  newsletterEnrollments, newsletterIssues, newsletterSequences, newsletterSequenceSteps,
  notificationDeliveries, notificationEvents, notificationPreferences, notificationSuppressions,
  relationshipConsents, relationshipExternalIdentities, relationshipNotes, relationships,
  relationshipTagAssignments, relationshipTags, relationshipTasks, users,
} from "@shared/schema";
import {
  createAudienceFormSchema, createLandingPageSchema, createNewsletterIssueSchema,
  createNewsletterSequenceSchema, publicAudienceSubmissionSchema, updatePublicPreferencesSchema,
} from "@shared/audience";
import { attachUser } from "./auth";
import { ensureDefaultBusiness, userCanManageBusiness } from "./businesses";
import { db } from "./db";
import { emitGovernedNotification } from "./audience";

const hashToken = (token: string) => createHash("sha256").update(token).digest("hex");
const publicId = (prefix: string) => `${prefix}_${randomBytes(12).toString("base64url")}`;
const plainText = (blocks: Array<Record<string, unknown>>) => blocks.map((block) => {
  const content = block.content && typeof block.content === "object" ? block.content as Record<string, unknown> : {};
  return [content.text, content.label, content.title, content.url].filter((value): value is string => typeof value === "string").join(" ");
}).filter(Boolean).join("\n\n").slice(0, 10_000);

function parseCsv(input: string) {
  const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false;
  for (let index = 0; index < input.length; index += 1) {
    const char = input[index];
    if (quoted) {
      if (char === '"' && input[index + 1] === '"') { cell += '"'; index += 1; }
      else if (char === '"') quoted = false;
      else cell += char;
    } else if (char === '"') quoted = true;
    else if (char === ",") { row.push(cell); cell = ""; }
    else if (char === "\n") { row.push(cell.replace(/\r$/, "")); rows.push(row); row = []; cell = ""; }
    else cell += char;
  }
  if (quoted) throw new Error("CSV contains an unclosed quoted field");
  if (cell.length || row.length) { row.push(cell.replace(/\r$/, "")); rows.push(row); }
  const [headers = [], ...records] = rows.filter((candidate) => candidate.some((value) => value.trim()));
  return records.map((values) => Object.fromEntries(headers.map((header, index) => [header.trim().toLowerCase(), values[index]?.trim() ?? ""])));
}

function csvCell(value: unknown) {
  let safe = value == null ? "" : String(value);
  if (/^[=+\-@]/.test(safe)) safe = `'${safe}`;
  return `"${safe.replaceAll('"', '""')}"`;
}

async function managedBusiness(userId: number) {
  const [user] = await db.select().from(users).where(eq(users.id, userId)).limit(1);
  if (!user) throw new Error("Authenticated user was not found");
  const business = await ensureDefaultBusiness(user);
  if (!await userCanManageBusiness(userId, business.id)) throw new Error("Business authority is required");
  return business;
}

async function upsertCapturedRelationship(input: { businessId: string; actorUserId: number | null; email: string; displayName: string; source: string; fields: Record<string, unknown>; tags: string[]; consentPurpose: string; disclosureVersion: string; consentGranted: boolean }) {
  return db.transaction(async (tx) => {
    let [identity] = await tx.select().from(relationshipExternalIdentities).where(and(eq(relationshipExternalIdentities.businessId, input.businessId), eq(relationshipExternalIdentities.provider, "email"), eq(relationshipExternalIdentities.providerSubjectId, input.email))).limit(1);
    let relationship = identity ? (await tx.select().from(relationships).where(eq(relationships.id, identity.relationshipId)).limit(1))[0] : undefined;
    if (!relationship) {
      [relationship] = await tx.insert(relationships).values({ businessId: input.businessId, createdByUserId: input.actorUserId, displayName: input.displayName, source: input.source, lifecycleStage: "new", customFields: input.fields }).returning();
      [identity] = await tx.insert(relationshipExternalIdentities).values({ businessId: input.businessId, relationshipId: relationship.id, provider: "email", providerSubjectId: input.email, address: input.email, displayName: input.displayName, verificationStatus: "observed", metadata: { source: input.source } }).returning();
    } else {
      [relationship] = await tx.update(relationships).set({ displayName: input.displayName || relationship.displayName, customFields: { ...relationship.customFields, ...input.fields }, lastInteractionAt: new Date(), updatedAt: new Date() }).where(eq(relationships.id, relationship.id)).returning();
    }
    const now = new Date();
    await tx.insert(audienceProfiles).values({ businessId: input.businessId, relationshipId: relationship.id, subscriberStatus: input.consentGranted ? "subscribed" : "prospect", lifecycleState: "new", acquisitionSource: input.source, interests: [], engagementScore: 10, fields: input.fields, subscribedAt: input.consentGranted ? now : null }).onConflictDoUpdate({ target: [audienceProfiles.businessId, audienceProfiles.relationshipId], set: { subscriberStatus: input.consentGranted ? "subscribed" : "prospect", acquisitionSource: input.source, fields: input.fields, subscribedAt: input.consentGranted ? now : null, updatedAt: now } });
    if (input.consentGranted) await tx.insert(relationshipConsents).values({ businessId: input.businessId, relationshipId: relationship.id, externalIdentityId: identity.id, purpose: input.consentPurpose, channel: "email", status: "granted", source: input.source, disclosureVersion: input.disclosureVersion, grantedAt: now, evidence: { explicit: true } });
    for (const name of input.tags) {
      let [tag] = await tx.insert(relationshipTags).values({ businessId: input.businessId, name }).onConflictDoNothing().returning();
      if (!tag) [tag] = await tx.select().from(relationshipTags).where(and(eq(relationshipTags.businessId, input.businessId), eq(relationshipTags.name, name))).limit(1);
      if (tag) await tx.insert(relationshipTagAssignments).values({ businessId: input.businessId, relationshipId: relationship.id, tagId: tag.id, assignedByUserId: input.actorUserId }).onConflictDoNothing();
    }
    return { relationship, identity };
  });
}

async function issueRecipients(issue: typeof newsletterIssues.$inferSelect) {
  if (issue.segmentId) {
    const rows = await db.select({ profile: audienceProfiles }).from(audienceSegmentMemberships).innerJoin(audienceProfiles, eq(audienceSegmentMemberships.relationshipId, audienceProfiles.relationshipId)).where(and(eq(audienceSegmentMemberships.segmentId, issue.segmentId), eq(audienceProfiles.subscriberStatus, "subscribed"))).limit(5_000);
    return rows.map((row) => row.profile);
  }
  return db.select().from(audienceProfiles).where(and(eq(audienceProfiles.businessId, issue.businessId), eq(audienceProfiles.subscriberStatus, "subscribed"))).limit(5_000);
}

export function registerAudienceStudioRoutes(app: Express) {
  app.get("/api/audience/studio", attachUser, async (req, res) => {
    const business = await managedBusiness(req.dbUser!.id);
    const [forms, landingPages, blocks, issues, sequences, profiles, deliveries] = await Promise.all([
      db.select().from(audienceForms).where(eq(audienceForms.businessId, business.id)).orderBy(desc(audienceForms.updatedAt)),
      db.select().from(audienceLandingPages).where(eq(audienceLandingPages.businessId, business.id)).orderBy(desc(audienceLandingPages.updatedAt)),
      db.select().from(newsletterBlocks).where(eq(newsletterBlocks.businessId, business.id)).orderBy(desc(newsletterBlocks.updatedAt)),
      db.select().from(newsletterIssues).where(eq(newsletterIssues.businessId, business.id)).orderBy(desc(newsletterIssues.updatedAt)),
      db.select().from(newsletterSequences).where(eq(newsletterSequences.businessId, business.id)).orderBy(desc(newsletterSequences.updatedAt)),
      db.select().from(audienceProfiles).where(eq(audienceProfiles.businessId, business.id)),
      db.select({ delivery: notificationDeliveries }).from(notificationDeliveries).innerJoin(notificationEvents, eq(notificationDeliveries.eventId, notificationEvents.id)).where(eq(notificationEvents.businessId, business.id)),
    ]);
    const subscribers = profiles.filter((profile) => profile.subscriberStatus === "subscribed").length;
    return res.json({ forms, landingPages, blocks, issues, sequences, metrics: { subscribers, forms: forms.length, issues: issues.length, sent: deliveries.filter((row) => ["sent", "delivered", "opened", "clicked"].includes(row.delivery.status)).length, opened: deliveries.filter((row) => ["opened", "clicked"].includes(row.delivery.status)).length, clicked: deliveries.filter((row) => row.delivery.status === "clicked").length } });
  });

  app.post("/api/audience/forms", attachUser, async (req, res) => {
    const parsed = createAudienceFormSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid form" }); const business = await managedBusiness(req.dbUser!.id);
    const [form] = await db.insert(audienceForms).values({ businessId: business.id, createdByUserId: req.dbUser!.id, publicId: publicId("form"), ...parsed.data }).returning(); return res.status(201).json(form);
  });
  app.post("/api/audience/forms/:id/publish", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const [form] = await db.update(audienceForms).set({ status: "published", updatedAt: new Date() }).where(and(eq(audienceForms.id, req.params.id), eq(audienceForms.businessId, business.id))).returning(); return form ? res.json(form) : res.status(404).json({ message: "Form not found" }); });
  app.get("/api/public/audience/forms/:publicId", async (req, res) => { const [form] = await db.select({ publicId: audienceForms.publicId, title: audienceForms.title, description: audienceForms.description, fields: audienceForms.fields, consentPurpose: audienceForms.consentPurpose, disclosureVersion: audienceForms.disclosureVersion, successMessage: audienceForms.successMessage }).from(audienceForms).where(and(eq(audienceForms.publicId, req.params.publicId), eq(audienceForms.status, "published"))).limit(1); return form ? res.json(form) : res.status(404).json({ message: "Form not found" }); });
  app.post("/api/public/audience/forms/:publicId/submissions", async (req, res) => {
    const parsed = publicAudienceSubmissionSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid submission" }); const [form] = await db.select().from(audienceForms).where(and(eq(audienceForms.publicId, req.params.publicId), eq(audienceForms.status, "published"))).limit(1); if (!form) return res.status(404).json({ message: "Form not found" });
    for (const field of form.fields) { const value = field.key === "email" ? parsed.data.email : parsed.data.values[field.key]; if (field.required && (value === undefined || value === null || String(value).trim() === "")) return res.status(400).json({ message: `${field.label} is required` }); if (field.type === "select" && value !== undefined && !field.options?.includes(String(value))) return res.status(400).json({ message: `${field.label} has an invalid option` }); }
    const captured = await upsertCapturedRelationship({ businessId: form.businessId, actorUserId: null, email: parsed.data.email, displayName: parsed.data.displayName ?? parsed.data.email.split("@")[0], source: `form:${form.id}`, fields: parsed.data.values, tags: form.tags, consentPurpose: form.consentPurpose, disclosureVersion: form.disclosureVersion, consentGranted: true });
    await db.insert(audienceFormSubmissions).values({ formId: form.id, relationshipId: captured.relationship.id, email: parsed.data.email, values: parsed.data.values, consentGranted: true }).onConflictDoUpdate({ target: [audienceFormSubmissions.formId, audienceFormSubmissions.relationshipId], set: { email: parsed.data.email, values: parsed.data.values, consentGranted: true, submittedAt: new Date() } });
    const active = await db.select().from(newsletterSequences).where(and(eq(newsletterSequences.businessId, form.businessId), eq(newsletterSequences.status, "active")));
    for (const sequence of active.filter((item) => item.trigger.type === "form_submission" && [form.id, form.publicId].includes(String(item.trigger.value ?? "")))) await db.insert(newsletterEnrollments).values({ sequenceId: sequence.id, relationshipId: captured.relationship.id }).onConflictDoNothing();
    return res.status(201).json({ accepted: true, message: form.successMessage });
  });

  app.post("/api/audience/landing-pages", attachUser, async (req, res) => { const parsed = createLandingPageSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid landing page" }); const business = await managedBusiness(req.dbUser!.id); if (parsed.data.formId) { const [form] = await db.select().from(audienceForms).where(and(eq(audienceForms.id, parsed.data.formId), eq(audienceForms.businessId, business.id))).limit(1); if (!form) return res.status(404).json({ message: "Form not found" }); } const [page] = await db.insert(audienceLandingPages).values({ businessId: business.id, createdByUserId: req.dbUser!.id, publicId: publicId("page"), ...parsed.data }).returning(); return res.status(201).json(page); });
  app.post("/api/audience/landing-pages/:id/publish", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const [page] = await db.update(audienceLandingPages).set({ status: "published", updatedAt: new Date() }).where(and(eq(audienceLandingPages.id, req.params.id), eq(audienceLandingPages.businessId, business.id))).returning(); return page ? res.json(page) : res.status(404).json({ message: "Page not found" }); });
  app.get("/api/public/audience/pages/:publicId", async (req, res) => { const [page] = await db.select().from(audienceLandingPages).where(and(eq(audienceLandingPages.publicId, req.params.publicId), eq(audienceLandingPages.status, "published"))).limit(1); if (!page) return res.status(404).json({ message: "Page not found" }); const [form] = page.formId ? await db.select({ publicId: audienceForms.publicId, title: audienceForms.title, description: audienceForms.description, fields: audienceForms.fields, consentPurpose: audienceForms.consentPurpose, disclosureVersion: audienceForms.disclosureVersion, successMessage: audienceForms.successMessage }).from(audienceForms).where(and(eq(audienceForms.id, page.formId), eq(audienceForms.status, "published"))).limit(1) : []; return res.json({ page: { publicId: page.publicId, headline: page.headline, subheadline: page.subheadline, sections: page.sections, theme: page.theme, seoTitle: page.seoTitle, seoDescription: page.seoDescription }, form: form ?? null }); });

  app.post("/api/audience/import", attachUser, async (req, res) => { const csv = typeof req.body?.csv === "string" ? req.body.csv : ""; if (!csv || Buffer.byteLength(csv) > 2_000_000) return res.status(400).json({ message: "CSV is required and must be under 2 MB" }); const business = await managedBusiness(req.dbUser!.id); let records: Array<Record<string, string>>; try { records = parseCsv(csv); } catch (error) { return res.status(400).json({ message: error instanceof Error ? error.message : "Invalid CSV" }); } if (records.length > 5_000) return res.status(400).json({ message: "Imports are limited to 5,000 rows per job" }); const results = { imported: 0, skipped: 0, errors: [] as Array<{ row: number; message: string }> }; for (let index = 0; index < records.length; index += 1) { const record = records[index]; const email = record.email?.toLowerCase(); if (!email || !/^\S+@\S+\.\S+$/.test(email)) { results.skipped += 1; results.errors.push({ row: index + 2, message: "Valid email required" }); continue; } try { await upsertCapturedRelationship({ businessId: business.id, actorUserId: req.dbUser!.id, email, displayName: record.name || email.split("@")[0], source: "csv_import", fields: Object.fromEntries(Object.entries(record).filter(([key]) => !["email", "name", "tags"].includes(key))), tags: (record.tags ?? "").split(";").map((tag) => tag.trim().toLowerCase()).filter(Boolean), consentPurpose: "marketing", disclosureVersion: "import-v1", consentGranted: record.consent?.toLowerCase() === "granted" }); results.imported += 1; } catch (error) { results.skipped += 1; results.errors.push({ row: index + 2, message: error instanceof Error ? error.message : "Import failed" }); } } return res.status(202).json(results); });
  app.get("/api/audience/export.csv", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const rows = await db.select({ relationship: relationships, profile: audienceProfiles, identity: relationshipExternalIdentities }).from(audienceProfiles).innerJoin(relationships, eq(audienceProfiles.relationshipId, relationships.id)).leftJoin(relationshipExternalIdentities, and(eq(relationshipExternalIdentities.relationshipId, relationships.id), eq(relationshipExternalIdentities.provider, "email"))).where(eq(audienceProfiles.businessId, business.id)).orderBy(asc(relationships.createdAt)); const csv = [["email", "name", "subscriber_status", "lifecycle_state", "acquisition_source", "engagement_score"].map(csvCell).join(","), ...rows.map((row) => [row.identity?.address, row.relationship.displayName, row.profile.subscriberStatus, row.profile.lifecycleState, row.profile.acquisitionSource, row.profile.engagementScore].map(csvCell).join(","))].join("\r\n"); res.setHeader("Content-Type", "text/csv; charset=utf-8"); res.setHeader("Content-Disposition", "attachment; filename=creativesos-audience.csv"); return res.send(csv); });

  app.post("/api/audience/newsletters/blocks", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const name = typeof req.body?.name === "string" ? req.body.name.trim().slice(0, 120) : ""; const kind = typeof req.body?.kind === "string" ? req.body.kind : ""; if (!name || !["text", "heading", "image", "button", "divider", "social", "product", "signature"].includes(kind)) return res.status(400).json({ message: "Valid block name and kind are required" }); const [block] = await db.insert(newsletterBlocks).values({ businessId: business.id, createdByUserId: req.dbUser!.id, name, kind, content: req.body?.content && typeof req.body.content === "object" ? req.body.content : {} }).returning(); return res.status(201).json(block); });
  app.post("/api/audience/newsletters/issues", attachUser, async (req, res) => { const parsed = createNewsletterIssueSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid newsletter" }); const business = await managedBusiness(req.dbUser!.id); if (parsed.data.segmentId) { const [segment] = await db.select().from(audienceSegments).where(and(eq(audienceSegments.id, parsed.data.segmentId), eq(audienceSegments.businessId, business.id))).limit(1); if (!segment) return res.status(404).json({ message: "Segment not found" }); } const status = parsed.data.scheduledAt && parsed.data.scheduledAt > new Date() ? "scheduled" : "draft"; const [issue] = await db.insert(newsletterIssues).values({ businessId: business.id, createdByUserId: req.dbUser!.id, ...parsed.data, status }).returning(); return res.status(201).json(issue); });
  app.post("/api/audience/newsletters/issues/:id/send", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const [issue] = await db.select().from(newsletterIssues).where(and(eq(newsletterIssues.id, req.params.id), eq(newsletterIssues.businessId, business.id))).limit(1); if (!issue) return res.status(404).json({ message: "Newsletter not found" }); if (["sending", "sent"].includes(issue.status)) return res.status(409).json({ message: "Newsletter has already been dispatched" }); const recipients = await issueRecipients(issue); await db.update(newsletterIssues).set({ status: "sending", updatedAt: new Date() }).where(eq(newsletterIssues.id, issue.id)); let accepted = 0; for (let index = 0; index < recipients.length; index += 1) { const recipient = recipients[index]; const variant = issue.variants.length ? issue.variants[index % issue.variants.length] : null; await emitGovernedNotification({ businessId: business.id, relationshipId: recipient.relationshipId, recipientUserId: null, eventType: "newsletter.issue", title: typeof variant?.subject === "string" ? variant.subject : issue.subject, body: plainText(issue.content), linkTo: null, purpose: "marketing", urgency: "normal", data: { issueId: issue.id, variant: variant?.key ?? "control" }, dedupeKey: `newsletter:${issue.id}:${recipient.relationshipId}`, scheduledAt: new Date(), channels: ["email"] }); accepted += 1; } const [updated] = await db.update(newsletterIssues).set({ status: "sent", sentAt: new Date(), updatedAt: new Date() }).where(eq(newsletterIssues.id, issue.id)).returning(); return res.status(202).json({ issue: updated, recipients: recipients.length, accepted }); });

  app.post("/api/audience/sequences", attachUser, async (req, res) => { const parsed = createNewsletterSequenceSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid sequence" }); const business = await managedBusiness(req.dbUser!.id); const result = await db.transaction(async (tx) => { const [sequence] = await tx.insert(newsletterSequences).values({ businessId: business.id, createdByUserId: req.dbUser!.id, name: parsed.data.name, trigger: parsed.data.trigger }).returning(); const steps = await tx.insert(newsletterSequenceSteps).values(parsed.data.steps.map((step) => ({ sequenceId: sequence.id, ...step }))).returning(); return { sequence, steps }; }); return res.status(201).json(result); });
  app.post("/api/audience/sequences/:id/activate", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const [sequence] = await db.update(newsletterSequences).set({ status: "active", updatedAt: new Date() }).where(and(eq(newsletterSequences.id, req.params.id), eq(newsletterSequences.businessId, business.id))).returning(); return sequence ? res.json(sequence) : res.status(404).json({ message: "Sequence not found" }); });
  app.post("/api/audience/sequences/:id/enroll", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const relationshipId = typeof req.body?.relationshipId === "string" ? req.body.relationshipId : ""; const [sequence] = await db.select().from(newsletterSequences).where(and(eq(newsletterSequences.id, req.params.id), eq(newsletterSequences.businessId, business.id), eq(newsletterSequences.status, "active"))).limit(1); const [profile] = await db.select().from(audienceProfiles).where(and(eq(audienceProfiles.relationshipId, relationshipId), eq(audienceProfiles.businessId, business.id), eq(audienceProfiles.subscriberStatus, "subscribed"))).limit(1); if (!sequence || !profile) return res.status(404).json({ message: "Active sequence or subscribed relationship not found" }); const [enrollment] = await db.insert(newsletterEnrollments).values({ sequenceId: sequence.id, relationshipId }).onConflictDoNothing().returning(); return res.status(201).json(enrollment ?? { enrolled: false }); });
  app.post("/api/audience/sequences/dispatch-due", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const due = await db.select({ enrollment: newsletterEnrollments, sequence: newsletterSequences }).from(newsletterEnrollments).innerJoin(newsletterSequences, eq(newsletterEnrollments.sequenceId, newsletterSequences.id)).where(and(eq(newsletterSequences.businessId, business.id), eq(newsletterSequences.status, "active"), eq(newsletterEnrollments.status, "active"), lte(newsletterEnrollments.nextRunAt, new Date()))).limit(500); let dispatched = 0; for (const row of due) { const [step] = await db.select().from(newsletterSequenceSteps).where(and(eq(newsletterSequenceSteps.sequenceId, row.sequence.id), eq(newsletterSequenceSteps.position, row.enrollment.nextStepPosition))).limit(1); if (!step) { await db.update(newsletterEnrollments).set({ status: "completed", completedAt: new Date(), updatedAt: new Date() }).where(eq(newsletterEnrollments.id, row.enrollment.id)); continue; } await emitGovernedNotification({ businessId: business.id, relationshipId: row.enrollment.relationshipId, recipientUserId: null, eventType: "newsletter.sequence", title: step.subject, body: plainText(step.content), linkTo: null, purpose: "marketing", urgency: "normal", data: { sequenceId: row.sequence.id, step: step.position }, dedupeKey: `sequence:${row.sequence.id}:${row.enrollment.relationshipId}:${step.position}`, scheduledAt: new Date(), channels: ["email"] }); const [next] = await db.select().from(newsletterSequenceSteps).where(and(eq(newsletterSequenceSteps.sequenceId, row.sequence.id), eq(newsletterSequenceSteps.position, step.position + 1))).limit(1); await db.update(newsletterEnrollments).set(next ? { nextStepPosition: next.position, nextRunAt: new Date(Date.now() + next.delayMinutes * 60_000), updatedAt: new Date() } : { status: "completed", completedAt: new Date(), updatedAt: new Date() }).where(eq(newsletterEnrollments.id, row.enrollment.id)); dispatched += 1; } return res.json({ due: due.length, dispatched }); });

  app.post("/api/audience/relationships/:relationshipId/preference-link", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const [relationship] = await db.select().from(relationships).where(and(eq(relationships.id, req.params.relationshipId), eq(relationships.businessId, business.id))).limit(1); if (!relationship) return res.status(404).json({ message: "Relationship not found" }); const token = randomBytes(32).toString("base64url"); const expiresAt = new Date(Date.now() + 90 * 24 * 60 * 60_000); await db.insert(audiencePreferenceTokens).values({ businessId: business.id, relationshipId: relationship.id, tokenHash: hashToken(token), expiresAt }); return res.status(201).json({ token, path: `/audience/preferences/${token}`, expiresAt }); });
  app.get("/api/public/audience/preferences/:token", async (req, res) => { const [record] = await db.select().from(audiencePreferenceTokens).where(and(eq(audiencePreferenceTokens.tokenHash, hashToken(req.params.token)), isNull(audiencePreferenceTokens.revokedAt), gt(audiencePreferenceTokens.expiresAt, new Date()))).limit(1); if (!record) return res.status(404).json({ message: "Preference link is invalid or expired" }); const preferences = await db.select().from(notificationPreferences).where(and(eq(notificationPreferences.businessId, record.businessId), eq(notificationPreferences.relationshipId, record.relationshipId), eq(notificationPreferences.channel, "email"), eq(notificationPreferences.purpose, "marketing"))); const suppressed = await db.select().from(notificationSuppressions).where(and(eq(notificationSuppressions.businessId, record.businessId), eq(notificationSuppressions.relationshipId, record.relationshipId), inArray(notificationSuppressions.channel, ["email", "all"]), inArray(notificationSuppressions.purpose, ["marketing", "all"]), or(isNull(notificationSuppressions.expiresAt), gt(notificationSuppressions.expiresAt, new Date()))!)); const preference = preferences[0]; return res.json({ marketingEmail: !suppressed.length && (preference?.enabled ?? true), digestCadence: preference?.digestCadence ?? "immediate", timezone: preference?.timezone ?? "UTC" }); });
  app.put("/api/public/audience/preferences/:token", async (req, res) => { const parsed = updatePublicPreferencesSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid preferences" }); const [record] = await db.select().from(audiencePreferenceTokens).where(and(eq(audiencePreferenceTokens.tokenHash, hashToken(req.params.token)), isNull(audiencePreferenceTokens.revokedAt), gt(audiencePreferenceTokens.expiresAt, new Date()))).limit(1); if (!record) return res.status(404).json({ message: "Preference link is invalid or expired" }); await db.insert(notificationPreferences).values({ businessId: record.businessId, relationshipId: record.relationshipId, userId: null, channel: "email", purpose: "marketing", enabled: parsed.data.marketingEmail, digestCadence: parsed.data.digestCadence, timezone: parsed.data.timezone }).onConflictDoUpdate({ target: [notificationPreferences.businessId, notificationPreferences.relationshipId, notificationPreferences.channel, notificationPreferences.purpose], targetWhere: sql`${notificationPreferences.relationshipId} is not null`, set: { enabled: parsed.data.marketingEmail, digestCadence: parsed.data.digestCadence, timezone: parsed.data.timezone, updatedAt: new Date() } }); if (!parsed.data.marketingEmail) { await db.insert(notificationSuppressions).values({ businessId: record.businessId, relationshipId: record.relationshipId, userId: null, channel: "email", purpose: "marketing", reason: "recipient_opt_out", source: "preference_center" }); await db.insert(relationshipConsents).values({ businessId: record.businessId, relationshipId: record.relationshipId, purpose: "marketing", channel: "email", status: "withdrawn", source: "preference_center", withdrawnAt: new Date(), evidence: { tokenId: record.id } }); await db.update(audienceProfiles).set({ subscriberStatus: "unsubscribed", unsubscribedAt: new Date(), updatedAt: new Date() }).where(and(eq(audienceProfiles.businessId, record.businessId), eq(audienceProfiles.relationshipId, record.relationshipId))); } return res.json({ saved: true }); });

  app.post("/api/audience/relationships/:relationshipId/handoff", attachUser, async (req, res) => { const business = await managedBusiness(req.dbUser!.id); const [relationship] = await db.select().from(relationships).where(and(eq(relationships.id, req.params.relationshipId), eq(relationships.businessId, business.id))).limit(1); if (!relationship) return res.status(404).json({ message: "Relationship not found" }); const reason = typeof req.body?.reason === "string" ? req.body.reason.trim().slice(0, 1_000) : "High-value audience activity"; const [task] = await db.insert(relationshipTasks).values({ businessId: business.id, relationshipId: relationship.id, createdByUserId: req.dbUser!.id, assignedToUserId: req.dbUser!.id, title: `Audience follow-up: ${relationship.displayName}`, body: reason, priority: "high" }).returning(); await db.insert(relationshipNotes).values({ businessId: business.id, relationshipId: relationship.id, authorUserId: req.dbUser!.id, body: `Audience Studio requested human intervention: ${reason}`, sourceType: "audience_handoff", sourceId: task.id }); return res.status(201).json(task); });
}
