import { createHash, randomBytes } from "node:crypto";
import { resolveTxt } from "node:dns/promises";
import type { Express, NextFunction, Request, Response } from "express";
import { and, asc, desc, eq, inArray, sql } from "drizzle-orm";
import { createCreatorSiteSchema, createCreatorSiteSectionSchema, creatorSiteRedirectSchema, creatorSiteSectionPayloadSchema } from "@shared/creator-site";
import { analyticsEvents, assets, creatorSiteDomains, creatorSiteRedirects, creatorSiteSections, creatorSites, users } from "@shared/schema";
import { attachUser } from "./auth";
import { ensureDefaultBusiness, userCanManageBusiness } from "./businesses";
import { db } from "./db";
import { assertAssetUsageAllowed, recordAssetUsage } from "./media-cloud";

type Handler = (req: Request, res: Response, next: NextFunction) => unknown;
const safe = (handler: Handler): Handler => (req, res, next) => { try { Promise.resolve(handler(req, res, next)).catch(next); } catch (error) { next(error); } };
const id = () => `site_${randomBytes(12).toString("base64url")}`;
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const normalizeDomain = (value: string) => value.trim().toLowerCase().replace(/^https?:\/\//, "").replace(/\/$/, "").split("/")[0].replace(/:\d+$/, "");

function validUrl(value: string, allowRelative = true) { if (allowRelative && value.startsWith("/") && !value.startsWith("//")) return true; try { return ["http:", "https:"].includes(new URL(value).protocol); } catch { return false; } }
function validatePayloadUrls(payload: ReturnType<typeof creatorSiteSectionPayloadSchema.parse>) {
  const urls: string[] = [];
  if (payload.type === "hero" && payload.ctaUrl) urls.push(payload.ctaUrl);
  if (payload.type === "links") urls.push(...payload.links.map((link) => link.url));
  if (["offers", "memberships", "communities", "events"].includes(payload.type)) urls.push(...(payload as Extract<typeof payload, { items: unknown }>).items.map((item) => item.url));
  if (payload.type === "embed") { if (!validUrl(payload.url, false)) return false; const host = new URL(payload.url).hostname.toLowerCase(); const allowed: Record<string, string[]> = { youtube: ["youtube.com", "www.youtube.com", "youtu.be"], vimeo: ["vimeo.com", "player.vimeo.com"], spotify: ["open.spotify.com"], creativesos: ["creativesos.net", "www.creativesos.net"] }; return allowed[payload.provider].includes(host); }
  return urls.every((url) => validUrl(url));
}
async function ownedSite(userId: number, siteId: string) { const [site] = await db.select().from(creatorSites).where(eq(creatorSites.id, siteId)).limit(1); return site && await userCanManageBusiness(userId, site.businessId) ? site : null; }
async function publicSite(where: { slug?: string; domain?: string }) { const condition = where.slug ? eq(creatorSites.slug, where.slug) : eq(creatorSiteDomains.domain, where.domain!); const rows = where.slug ? await db.select({ site: creatorSites }).from(creatorSites).where(and(condition, eq(creatorSites.status, "published"))).limit(1) : await db.select({ site: creatorSites }).from(creatorSiteDomains).innerJoin(creatorSites, eq(creatorSiteDomains.siteId, creatorSites.id)).where(and(condition, eq(creatorSiteDomains.status, "active"), eq(creatorSites.status, "published"))).limit(1); return rows[0]?.site ?? null; }
async function publicPayload(site: typeof creatorSites.$inferSelect) { const sections = await db.select().from(creatorSiteSections).where(and(eq(creatorSiteSections.siteId, site.id), eq(creatorSiteSections.visibility, "public"))).orderBy(asc(creatorSiteSections.sortOrder)); const assetIds = Array.from(new Set([site.avatarAssetId, site.seo.imageAssetId, ...sections.flatMap((section) => section.payload.type === "media" ? section.payload.assetIds : ["offers", "memberships", "communities", "events"].includes(section.payload.type) ? (section.payload as { items: Array<{ imageAssetId: string | null }> }).items.map((item) => item.imageAssetId) : [])].filter((value): value is string => Boolean(value)))); const media = assetIds.length ? await db.select({ id: assets.id, url: assets.publicUrl, mimeType: assets.mimeType, alt: assets.originalFilename }).from(assets).where(and(inArray(assets.id, assetIds), eq(assets.visibility, "public"), eq(assets.status, "ready"))) : []; return { site: { publicId: site.publicId, slug: site.slug, name: site.name, tagline: site.tagline, bio: site.bio, avatarAssetId: site.avatarAssetId, theme: site.theme, seo: site.seo }, sections: sections.map(({ id: sectionId, name, kind, payload, sortOrder }) => ({ id: sectionId, name, kind, payload, sortOrder })), media };
}

export function registerCreatorSiteRoutes(base: Express) {
  const app = { get: (path: string, ...handlers: Handler[]) => base.get(path, ...handlers.map(safe)), post: (path: string, ...handlers: Handler[]) => base.post(path, ...handlers.map(safe)), patch: (path: string, ...handlers: Handler[]) => base.patch(path, ...handlers.map(safe)), delete: (path: string, ...handlers: Handler[]) => base.delete(path, ...handlers.map(safe)) };
  app.get("/api/sites", attachUser, async (req, res) => { const [user] = await db.select().from(users).where(eq(users.id, req.dbUser!.id)).limit(1); if (!user) return res.status(401).json({ message: "Account not found" }); const business = await ensureDefaultBusiness(user); const [site] = await db.select().from(creatorSites).where(eq(creatorSites.businessId, business.id)).limit(1); if (!site) return res.json({ site: null, sections: [], redirects: [], domains: [], metrics: [] }); const [sections, redirects, domains, metrics] = await Promise.all([db.select().from(creatorSiteSections).where(eq(creatorSiteSections.siteId, site.id)).orderBy(asc(creatorSiteSections.sortOrder)), db.select().from(creatorSiteRedirects).where(eq(creatorSiteRedirects.siteId, site.id)).orderBy(desc(creatorSiteRedirects.updatedAt)), db.select({ id: creatorSiteDomains.id, domain: creatorSiteDomains.domain, status: creatorSiteDomains.status, verificationTokenHint: creatorSiteDomains.verificationTokenHint, verifiedAt: creatorSiteDomains.verifiedAt, lastCheckedAt: creatorSiteDomains.lastCheckedAt, errorCode: creatorSiteDomains.errorCode }).from(creatorSiteDomains).where(eq(creatorSiteDomains.siteId, site.id)), db.select({ eventName: analyticsEvents.eventName, count: sql<number>`count(*)::int`, visitors: sql<number>`count(distinct coalesce(${analyticsEvents.userId}::text, ${analyticsEvents.anonymousId}))::int` }).from(analyticsEvents).where(and(eq(analyticsEvents.objectType, "site"), eq(analyticsEvents.objectId, site.id))).groupBy(analyticsEvents.eventName)]); return res.json({ site, sections, redirects, domains, metrics }); });
  app.post("/api/sites", attachUser, async (req, res) => { const parsed = createCreatorSiteSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid site" }); const [user] = await db.select().from(users).where(eq(users.id, req.dbUser!.id)).limit(1); if (!user) return res.status(401).json({ message: "Account not found" }); const business = await ensureDefaultBusiness(user); if (parsed.data.avatarAssetId) { const [asset] = await db.select().from(assets).where(and(eq(assets.id, parsed.data.avatarAssetId), eq(assets.ownerUserId, req.dbUser!.id), eq(assets.visibility, "public"), eq(assets.status, "ready"))).limit(1); if (!asset) return res.status(404).json({ message: "Public avatar asset not found" }); await assertAssetUsageAllowed(asset.id, "native_publish"); } if (parsed.data.seo.imageAssetId) await assertAssetUsageAllowed(parsed.data.seo.imageAssetId, "native_publish"); const [site] = await db.insert(creatorSites).values({ businessId: business.id, ownerUserId: req.dbUser!.id, publicId: id(), ...parsed.data }).onConflictDoUpdate({ target: creatorSites.businessId, set: { ...parsed.data, revision: sql`${creatorSites.revision} + 1`, updatedAt: new Date() } }).returning(); for (const assetId of [site.avatarAssetId, site.seo.imageAssetId].filter((value): value is string => Boolean(value))) await recordAssetUsage({ assetId, actorUserId: req.dbUser!.id, surfaceType: "site", surfaceId: site.id, useType: "native_publish" }); return res.status(201).json(site); });
  app.post("/api/sites/:id/publish", attachUser, async (req, res) => { const site = await ownedSite(req.dbUser!.id, req.params.id); if (!site) return res.status(404).json({ message: "Site not found" }); const [sections] = await db.select({ count: sql<number>`count(*)::int` }).from(creatorSiteSections).where(and(eq(creatorSiteSections.siteId, site.id), eq(creatorSiteSections.visibility, "public"))); if (!sections.count) return res.status(409).json({ message: "Add at least one public section before publishing" }); const [updated] = await db.update(creatorSites).set({ status: "published", updatedAt: new Date() }).where(eq(creatorSites.id, site.id)).returning(); return res.json({ ...updated, url: `${process.env.PUBLIC_APP_URL ?? "https://creativesos.net"}/s/${updated.slug}` }); });
  app.post("/api/sites/:id/sections", attachUser, async (req, res) => { const parsed = createCreatorSiteSectionSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid section" }); if (!validatePayloadUrls(parsed.data.payload)) return res.status(400).json({ message: "Section contains an unsafe or unsupported URL" }); const site = await ownedSite(req.dbUser!.id, req.params.id); if (!site) return res.status(404).json({ message: "Site not found" }); if (parsed.data.payload.type === "media") { const owned = await db.select().from(assets).where(and(inArray(assets.id, parsed.data.payload.assetIds), eq(assets.ownerUserId, req.dbUser!.id), eq(assets.visibility, "public"), eq(assets.status, "ready"))); if (owned.length !== new Set(parsed.data.payload.assetIds).size) return res.status(404).json({ message: "Every media item must be a public owned asset" }); for (const asset of owned) { await assertAssetUsageAllowed(asset.id, "native_publish"); await recordAssetUsage({ assetId: asset.id, actorUserId: req.dbUser!.id, surfaceType: "site", surfaceId: site.id, useType: "native_publish" }); } } const [section] = await db.insert(creatorSiteSections).values({ siteId: site.id, name: parsed.data.name, kind: parsed.data.payload.type, payload: parsed.data.payload, sortOrder: parsed.data.sortOrder, visibility: parsed.data.visibility }).returning(); return res.status(201).json(section); });
  app.delete("/api/sites/:id/sections/:sectionId", attachUser, async (req, res) => { const site = await ownedSite(req.dbUser!.id, req.params.id); if (!site) return res.status(404).json({ message: "Site not found" }); const [removed] = await db.delete(creatorSiteSections).where(and(eq(creatorSiteSections.id, req.params.sectionId), eq(creatorSiteSections.siteId, site.id))).returning(); return removed ? res.status(204).send() : res.status(404).json({ message: "Section not found" }); });
  app.post("/api/sites/:id/redirects", attachUser, async (req, res) => { const parsed = creatorSiteRedirectSchema.safeParse(req.body); if (!parsed.success || !validUrl(parsed.data?.targetUrl ?? "")) return res.status(400).json({ message: parsed.success ? "Unsafe redirect target" : parsed.error.issues[0]?.message ?? "Invalid redirect" }); const site = await ownedSite(req.dbUser!.id, req.params.id); if (!site) return res.status(404).json({ message: "Site not found" }); const [redirect] = await db.insert(creatorSiteRedirects).values({ siteId: site.id, ...parsed.data }).onConflictDoUpdate({ target: [creatorSiteRedirects.siteId, creatorSiteRedirects.sourcePath], set: { targetUrl: parsed.data.targetUrl, statusCode: parsed.data.statusCode, updatedAt: new Date() } }).returning(); return res.status(201).json(redirect); });
  app.post("/api/sites/:id/domains", attachUser, async (req, res) => { const site = await ownedSite(req.dbUser!.id, req.params.id); const domain = normalizeDomain(String(req.body?.domain ?? "")); if (!site) return res.status(404).json({ message: "Site not found" }); if (!/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(domain)) return res.status(400).json({ message: "Valid custom domain required" }); const token = randomBytes(24).toString("base64url"); const value = `creativesos-site-verification=${token}`; const [record] = await db.insert(creatorSiteDomains).values({ siteId: site.id, domain, verificationTokenHash: hash(value), verificationTokenHint: value.slice(-8) }).onConflictDoUpdate({ target: creatorSiteDomains.domain, set: { siteId: site.id, verificationTokenHash: hash(value), verificationTokenHint: value.slice(-8), status: "pending", verifiedAt: null, errorCode: null, updatedAt: new Date() } }).returning(); return res.status(201).json({ id: record.id, domain, dns: { type: "TXT", name: `_creativesos.${domain}`, value }, status: record.status }); });
  app.post("/api/sites/:id/domains/:domainId/verify", attachUser, async (req, res) => { const site = await ownedSite(req.dbUser!.id, req.params.id); const [record] = site ? await db.select().from(creatorSiteDomains).where(and(eq(creatorSiteDomains.id, req.params.domainId), eq(creatorSiteDomains.siteId, site.id))).limit(1) : []; if (!site || !record) return res.status(404).json({ message: "Domain not found" }); let matched = false; try { const rows = await resolveTxt(`_creativesos.${record.domain}`); matched = rows.map((parts) => parts.join("")).some((value) => hash(value) === record.verificationTokenHash); } catch { matched = false; } const [updated] = await db.update(creatorSiteDomains).set({ status: matched ? "active" : "pending", verifiedAt: matched ? new Date() : null, lastCheckedAt: new Date(), errorCode: matched ? null : "dns_value_not_observed", updatedAt: new Date() }).where(eq(creatorSiteDomains.id, record.id)).returning(); return res.status(matched ? 200 : 409).json(updated); });
  app.get("/api/public/sites/:slug", async (req, res) => { const site = await publicSite({ slug: req.params.slug.toLowerCase() }); return site ? res.json(await publicPayload(site)) : res.status(404).json({ message: "Site not found" }); });
  app.get("/api/public/sites-domain", async (req, res) => { const domain = normalizeDomain(String(req.query.domain ?? req.headers.host ?? "")); const site = await publicSite({ domain }); return site ? res.json(await publicPayload(site)) : res.status(404).json({ message: "Site not found" }); });
  app.get("/api/public/sites/:slug/go/*", async (req, res) => { const site = await publicSite({ slug: req.params.slug.toLowerCase() }); const sourcePath = `/${String(req.params[0] ?? "")}`; const [redirect] = site ? await db.select().from(creatorSiteRedirects).where(and(eq(creatorSiteRedirects.siteId, site.id), eq(creatorSiteRedirects.sourcePath, sourcePath))).limit(1) : []; if (!site || !redirect) return res.status(404).send("Link not found"); await db.update(creatorSiteRedirects).set({ hits: sql`${creatorSiteRedirects.hits} + 1`, updatedAt: new Date() }).where(eq(creatorSiteRedirects.id, redirect.id)); return res.redirect(redirect.statusCode, redirect.targetUrl); });
  app.post("/api/public/sites/:slug/events", async (req, res) => { const site = await publicSite({ slug: req.params.slug.toLowerCase() }); if (!site) return res.status(404).json({ message: "Site not found" }); if (req.body?.consentState !== "analytics") return res.status(202).json({ accepted: false, status: "suppressed" }); const kind = ["view", "click", "subscribe"].includes(String(req.body?.event)) ? String(req.body.event) : "view"; const sessionId = typeof req.body?.sessionId === "string" && req.body.sessionId.length >= 8 ? req.body.sessionId.slice(0, 180) : randomBytes(12).toString("hex"); const anonymousId = hash(String(req.body?.anonymousId ?? sessionId)).slice(0, 32); const sequence = Number.isInteger(req.body?.sequence) ? Math.max(0, Number(req.body.sequence)) : 0; const [event] = await db.insert(analyticsEvents).values({ businessId: site.businessId, anonymousId, sessionId, eventName: `site.${kind}`, objectType: "site", objectId: site.id, source: "creator_site", deduplicationKey: `site:${site.id}:${kind}:${anonymousId}:${sessionId}:${sequence}`.slice(0, 200), consentState: "analytics", occurredAt: new Date(), properties: { sectionId: typeof req.body?.sectionId === "string" ? req.body.sectionId.slice(0, 120) : null, target: typeof req.body?.target === "string" ? req.body.target.slice(0, 500) : null } }).onConflictDoNothing().returning(); return res.status(202).json({ accepted: Boolean(event) }); });
}
