import { createHash, randomBytes } from "node:crypto";
import type { Express, NextFunction, Request, Response } from "express";
import { and, asc, desc, eq, gt, inArray, isNull, lte, sql } from "drizzle-orm";
import { createPodcastEpisodeSchema, createPodcastSeasonSchema, createPodcastShowSchema, podcastPollSchema } from "@shared/podcast";
import { analyticsEvents, assets, entitlements, mediaTextTracks, podcastDestinations, podcastEpisodeComments, podcastEpisodes, podcastPollVotes, podcastPolls, podcastPrivateFeedTokens, podcastSeasons, podcastShows, products, users } from "@shared/schema";
import { attachUser } from "./auth";
import { createPrivateAssetReadUrl } from "./asset-storage";
import { ensureDefaultBusiness, userCanManageBusiness } from "./businesses";
import { db } from "./db";
import { assertAssetUsageAllowed, recordAssetUsage } from "./media-cloud";

const tokenHash = (token: string) => createHash("sha256").update(token).digest("hex");
const id = (prefix: string) => `${prefix}_${randomBytes(12).toString("base64url")}`;
const xml = (value: unknown) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&apos;");
const cdata = (value: unknown) => `<![CDATA[${String(value ?? "").replaceAll("]]>", "]]]]><![CDATA[>")}]]>`;
const appUrl = () => (process.env.PUBLIC_APP_URL ?? "https://creativesos.net").replace(/\/$/, "");

async function businessFor(userId: number) { const [user] = await db.select().from(users).where(eq(users.id, userId)).limit(1); if (!user) throw new Error("User not found"); return ensureDefaultBusiness(user); }
async function ownedShow(userId: number, showId: string) { const [show] = await db.select().from(podcastShows).where(eq(podcastShows.id, showId)).limit(1); return show && await userCanManageBusiness(userId, show.businessId) ? show : null; }
async function episodeWithShow(episodeId: string) { return (await db.select({ episode: podcastEpisodes, show: podcastShows }).from(podcastEpisodes).innerJoin(podcastShows, eq(podcastEpisodes.showId, podcastShows.id)).where(eq(podcastEpisodes.id, episodeId)).limit(1))[0] ?? null; }
async function userCanAccessShow(userId: number, show: typeof podcastShows.$inferSelect) { if (show.access === "public" || show.ownerUserId === userId) return true; if (!show.entitlementProductId) return false; const [access] = await db.select().from(entitlements).where(and(eq(entitlements.userId, userId), eq(entitlements.productId, show.entitlementProductId), eq(entitlements.status, "active"))).limit(1); return Boolean(access && (!access.endsAt || access.endsAt > new Date())); }
async function validFeedToken(showId: string, token: string) { const [record] = await db.select().from(podcastPrivateFeedTokens).where(and(eq(podcastPrivateFeedTokens.showId, showId), eq(podcastPrivateFeedTokens.tokenHash, tokenHash(token)), isNull(podcastPrivateFeedTokens.revokedAt), gt(podcastPrivateFeedTokens.expiresAt, new Date()))).limit(1); return record ?? null; }
function playbackInput(body: unknown) {
  const input = body && typeof body === "object" ? body as Record<string, unknown> : {};
  const action = ["start", "progress", "complete"].includes(String(input.event)) ? String(input.event) : "progress";
  const sessionId = typeof input.sessionId === "string" && input.sessionId.length >= 8 ? input.sessionId.slice(0, 180) : randomBytes(12).toString("hex");
  const sequence = Number.isInteger(input.sequence) ? Math.max(0, Number(input.sequence)) : 0;
  const positionSeconds = Number.isFinite(Number(input.positionSeconds)) ? Math.max(0, Number(input.positionSeconds)) : 0;
  return { eventName: `podcast.${action}`, sessionId, sequence, positionSeconds };
}
async function recordPlayback(input: { row: Awaited<ReturnType<typeof episodeWithShow>> & {}; userId?: number; anonymousId?: string; body: unknown }) {
  const parsed = playbackInput(input.body);
  const actor = input.userId ? `user:${input.userId}` : `anonymous:${input.anonymousId}`;
  const [event] = await db.insert(analyticsEvents).values({ businessId: input.row.show.businessId, userId: input.userId ?? null, anonymousId: input.anonymousId ?? null, sessionId: parsed.sessionId, eventName: parsed.eventName, objectType: "podcast_episode", objectId: input.row.episode.id, source: "podcast_player", deduplicationKey: `podcast:${input.row.episode.id}:${actor}:${parsed.sessionId}:${parsed.sequence}`.slice(0, 200), consentState: "analytics", properties: { positionSeconds: parsed.positionSeconds }, occurredAt: new Date() }).onConflictDoNothing().returning();
  return Boolean(event);
}

async function feedXml(show: typeof podcastShows.$inferSelect, token?: string) {
  const episodes = await db.select({ episode: podcastEpisodes, media: assets }).from(podcastEpisodes).innerJoin(assets, eq(podcastEpisodes.mediaAssetId, assets.id)).where(and(eq(podcastEpisodes.showId, show.id), eq(podcastEpisodes.status, "published"))).orderBy(desc(podcastEpisodes.publishedAt));
  const artwork = show.artworkAssetId ? (await db.select().from(assets).where(eq(assets.id, show.artworkAssetId)).limit(1))[0] : null;
  const feedUrl = token ? `${appUrl()}/api/podcasts/feed/${show.publicId}/${token}.xml` : `${appUrl()}/api/podcasts/feed/${show.publicId}.xml`;
  const items = await Promise.all(episodes.map(async ({ episode, media }) => {
    const tracks = await db.select().from(mediaTextTracks).where(and(eq(mediaTextTracks.assetId, media.id), inArray(mediaTextTracks.kind, ["transcript", "chapters"]))).orderBy(asc(mediaTextTracks.createdAt));
    const enclosure = `${appUrl()}/api/podcasts/episodes/${episode.publicId}/media${token ? `?token=${encodeURIComponent(token)}` : ""}`;
    const chapters = episode.chapters.length ? `${appUrl()}/api/podcasts/episodes/${episode.publicId}/chapters.json${token ? `?token=${encodeURIComponent(token)}` : ""}` : null;
    return `<item><title>${xml(episode.title)}</title><description>${cdata(episode.description)}</description><guid isPermaLink="false">${xml(episode.publicId)}</guid><link>${xml(`${appUrl()}/podcasts/${show.publicId}/episodes/${episode.publicId}`)}</link><pubDate>${(episode.publishedAt ?? episode.createdAt).toUTCString()}</pubDate><enclosure url="${xml(enclosure)}" length="${media.sizeBytes ?? 0}" type="${xml(media.mimeType ?? "audio/mpeg")}"/><itunes:episodeType>${xml(episode.episodeType)}</itunes:episodeType>${episode.episodeNumber ? `<itunes:episode>${episode.episodeNumber}</itunes:episode>` : ""}${episode.durationSeconds ? `<itunes:duration>${episode.durationSeconds}</itunes:duration>` : ""}<itunes:explicit>${episode.explicit ? "true" : "false"}</itunes:explicit>${chapters ? `<podcast:chapters url="${xml(chapters)}" type="application/json+chapters"/>` : ""}${tracks.filter((track) => track.kind === "transcript" && track.publicUrl).map((track) => `<podcast:transcript url="${xml(track.publicUrl)}" type="${xml(track.mimeType)}" language="${xml(track.language)}"/>`).join("")}</item>`;
  }));
  return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:podcast="https://podcastindex.org/namespace/1.0"><channel><title>${xml(show.title)}</title><link>${xml(show.websiteUrl ?? `${appUrl()}/podcasts/${show.publicId}`)}</link><atom:link href="${xml(feedUrl)}" rel="self" type="application/rss+xml"/><description>${cdata(show.description)}</description><language>${xml(show.language)}</language><itunes:author>${xml(show.author)}</itunes:author><itunes:owner><itunes:name>${xml(show.author)}</itunes:name><itunes:email>${xml(show.ownerEmail)}</itunes:email></itunes:owner><itunes:category text="${xml(show.category)}"/><itunes:explicit>${show.explicit ? "true" : "false"}</itunes:explicit>${artwork?.publicUrl ? `<itunes:image href="${xml(artwork.publicUrl)}"/>` : ""}<copyright>${xml(show.copyright)}</copyright>${items.join("")}</channel></rss>`;
}

function importedItems(source: string) {
  const matches = source.match(/<item\b[\s\S]*?<\/item>/gi) ?? [];
  const text = (item: string, tag: string) => (item.match(new RegExp(`<${tag}(?:\\s[^>]*)?>(?:<!\\[CDATA\\[)?([\\s\\S]*?)(?:\\]\\]>)?<\\/${tag}>`, "i"))?.[1] ?? "").replace(/<[^>]+>/g, "").trim();
  return matches.slice(0, 500).map((item, index) => ({ title: text(item, "title") || `Imported episode ${index + 1}`, description: text(item, "description"), enclosure: item.match(/<enclosure\b[^>]*url=["']([^"']+)["'][^>]*>/i)?.[1] ?? "", mimeType: item.match(/<enclosure\b[^>]*type=["']([^"']+)["'][^>]*>/i)?.[1] ?? "audio/mpeg", publishedAt: new Date(text(item, "pubDate") || Date.now()) }));
}

type RouteHandler = (req: Request, res: Response, next: NextFunction) => unknown;

function guarded(handler: RouteHandler): RouteHandler {
  return (req, res, next) => {
    try {
      Promise.resolve(handler(req, res, next)).catch(next);
    } catch (error) {
      next(error);
    }
  };
}

export function registerPodcastRoutes(baseApp: Express) {
  const app = {
    get: (path: string, ...handlers: RouteHandler[]) => baseApp.get(path, ...handlers.map(guarded)),
    post: (path: string, ...handlers: RouteHandler[]) => baseApp.post(path, ...handlers.map(guarded)),
  };
  app.get("/api/podcasts", attachUser, async (req, res) => { const business = await businessFor(req.dbUser!.id); const shows = await db.select().from(podcastShows).where(eq(podcastShows.businessId, business.id)).orderBy(desc(podcastShows.updatedAt)); const episodes = shows.length ? await db.select().from(podcastEpisodes).where(inArray(podcastEpisodes.showId, shows.map((show) => show.id))).orderBy(desc(podcastEpisodes.updatedAt)) : []; const destinations = shows.length ? await db.select().from(podcastDestinations).where(inArray(podcastDestinations.showId, shows.map((show) => show.id))) : []; return res.json({ shows, episodes, destinations }); });
  app.post("/api/podcasts", attachUser, async (req, res) => { const parsed = createPodcastShowSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid show" }); const business = await businessFor(req.dbUser!.id); if (parsed.data.entitlementProductId) { const [product] = await db.select().from(products).where(and(eq(products.id, parsed.data.entitlementProductId), eq(products.userId, req.dbUser!.id))).limit(1); if (!product) return res.status(404).json({ message: "Entitlement product not found" }); } if (parsed.data.artworkAssetId) await assertAssetUsageAllowed(parsed.data.artworkAssetId, "artwork"); const [show] = await db.insert(podcastShows).values({ businessId: business.id, ownerUserId: req.dbUser!.id, publicId: id("show"), ...parsed.data }).returning(); if (show.artworkAssetId) await recordAssetUsage({ assetId: show.artworkAssetId, actorUserId: req.dbUser!.id, surfaceType: "podcast", surfaceId: show.id, useType: "artwork" }); return res.status(201).json(show); });
  app.post("/api/podcasts/:id/publish", attachUser, async (req, res) => { const show = await ownedShow(req.dbUser!.id, req.params.id); if (!show) return res.status(404).json({ message: "Show not found" }); const [updated] = await db.update(podcastShows).set({ status: "published", updatedAt: new Date() }).where(eq(podcastShows.id, show.id)).returning(); return res.json({ ...updated, feedUrl: `${appUrl()}/api/podcasts/feed/${show.publicId}.xml` }); });
  app.post("/api/podcasts/:id/redirect", attachUser, async (req, res) => { const show = await ownedShow(req.dbUser!.id, req.params.id); const redirectUrl = typeof req.body?.redirectUrl === "string" ? req.body.redirectUrl.trim() : ""; if (!show) return res.status(404).json({ message: "Show not found" }); try { const url = new URL(redirectUrl); if (!['http:', 'https:'].includes(url.protocol)) throw new Error(); } catch { return res.status(400).json({ message: "A valid HTTP redirect URL is required" }); } const [updated] = await db.update(podcastShows).set({ redirectUrl, updatedAt: new Date() }).where(eq(podcastShows.id, show.id)).returning(); return res.json(updated); });
  app.post("/api/podcasts/:id/seasons", attachUser, async (req, res) => { const parsed = createPodcastSeasonSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid season" }); const show = await ownedShow(req.dbUser!.id, req.params.id); if (!show) return res.status(404).json({ message: "Show not found" }); const [season] = await db.insert(podcastSeasons).values({ showId: show.id, ...parsed.data }).returning(); return res.status(201).json(season); });
  app.post("/api/podcasts/:id/episodes", attachUser, async (req, res) => { const parsed = createPodcastEpisodeSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid episode" }); const show = await ownedShow(req.dbUser!.id, req.params.id); if (!show) return res.status(404).json({ message: "Show not found" }); const assetIds = [parsed.data.mediaAssetId, parsed.data.videoAssetId, parsed.data.artworkAssetId].filter((value): value is string => Boolean(value)); const owned = await db.select().from(assets).where(and(inArray(assets.id, assetIds), eq(assets.ownerUserId, req.dbUser!.id), eq(assets.status, "ready"))); if (owned.length !== new Set(assetIds).size) return res.status(404).json({ message: "Every episode asset must be ready and owned by the creator" }); const media = owned.find((asset) => asset.id === parsed.data.mediaAssetId)!; if (!media.mimeType?.startsWith("audio/") && !media.mimeType?.startsWith("video/")) return res.status(400).json({ message: "Episode media must be audio or video" }); await assertAssetUsageAllowed(media.id, "native_publish"); if (parsed.data.seasonId) { const [season] = await db.select().from(podcastSeasons).where(and(eq(podcastSeasons.id, parsed.data.seasonId), eq(podcastSeasons.showId, show.id))).limit(1); if (!season) return res.status(404).json({ message: "Season not found" }); } const status = parsed.data.scheduledAt && parsed.data.scheduledAt > new Date() ? "scheduled" : "draft"; const [episode] = await db.insert(podcastEpisodes).values({ showId: show.id, createdByUserId: req.dbUser!.id, publicId: id("episode"), ...parsed.data, status }).returning(); for (const assetId of assetIds) await recordAssetUsage({ assetId, actorUserId: req.dbUser!.id, surfaceType: "podcast", surfaceId: episode.id, useType: assetId === parsed.data.artworkAssetId ? "artwork" : "native_publish" }); return res.status(201).json(episode); });
  app.post("/api/podcasts/episodes/:id/publish", attachUser, async (req, res) => { const row = await episodeWithShow(req.params.id); if (!row || !await userCanManageBusiness(req.dbUser!.id, row.show.businessId)) return res.status(404).json({ message: "Episode not found" }); if (row.show.status !== "published") return res.status(409).json({ message: "Publish the show before publishing episodes" }); const [episode] = await db.update(podcastEpisodes).set({ status: "published", publishedAt: new Date(), updatedAt: new Date() }).where(eq(podcastEpisodes.id, row.episode.id)).returning(); return res.json(episode); });
  app.post("/api/podcasts/dispatch-due", attachUser, async (req, res) => { const business = await businessFor(req.dbUser!.id); const due = await db.select({ episode: podcastEpisodes, show: podcastShows }).from(podcastEpisodes).innerJoin(podcastShows, eq(podcastEpisodes.showId, podcastShows.id)).where(and(eq(podcastShows.businessId, business.id), eq(podcastShows.status, "published"), eq(podcastEpisodes.status, "scheduled"), lte(podcastEpisodes.scheduledAt, new Date()))).limit(250); if (!due.length) return res.json({ published: 0, episodeIds: [] }); const episodeIds = due.map(({ episode }) => episode.id); await db.update(podcastEpisodes).set({ status: "published", publishedAt: new Date(), updatedAt: new Date() }).where(inArray(podcastEpisodes.id, episodeIds)); return res.json({ published: episodeIds.length, episodeIds }); });
  app.get("/api/podcasts/:id", attachUser, async (req, res) => { const show = await ownedShow(req.dbUser!.id, req.params.id); if (!show) return res.status(404).json({ message: "Show not found" }); const [seasons, episodes, destinations] = await Promise.all([db.select().from(podcastSeasons).where(eq(podcastSeasons.showId, show.id)).orderBy(asc(podcastSeasons.number)), db.select().from(podcastEpisodes).where(eq(podcastEpisodes.showId, show.id)).orderBy(desc(podcastEpisodes.createdAt)), db.select().from(podcastDestinations).where(eq(podcastDestinations.showId, show.id))]); return res.json({ show, seasons, episodes, destinations }); });
  app.get("/api/public/podcasts/:publicId", async (req, res) => { const [show] = await db.select().from(podcastShows).where(and(eq(podcastShows.publicId, req.params.publicId), eq(podcastShows.status, "published"), eq(podcastShows.access, "public"))).limit(1); if (!show) return res.status(404).json({ message: "Show not found" }); const episodes = await db.select().from(podcastEpisodes).where(and(eq(podcastEpisodes.showId, show.id), eq(podcastEpisodes.status, "published"), inArray(podcastEpisodes.access, ["show_default", "public"]))).orderBy(desc(podcastEpisodes.publishedAt)); return res.json({ show: { publicId: show.publicId, title: show.title, description: show.description, author: show.author, artworkAssetId: show.artworkAssetId, category: show.category, explicit: show.explicit }, episodes: episodes.map((episode) => ({ publicId: episode.publicId, title: episode.title, description: episode.description, episodeType: episode.episodeType, episodeNumber: episode.episodeNumber, durationSeconds: episode.durationSeconds, chapters: episode.chapters, publishedAt: episode.publishedAt, mediaUrl: `/api/podcasts/episodes/${episode.publicId}/media` })) }); });
  app.post("/api/public/podcasts/:publicId/private-feed", attachUser, async (req, res) => { const [show] = await db.select().from(podcastShows).where(and(eq(podcastShows.publicId, req.params.publicId), eq(podcastShows.status, "published"))).limit(1); if (!show) return res.status(404).json({ message: "Show not found" }); if (!await userCanAccessShow(req.dbUser!.id, show)) return res.status(403).json({ message: "An active membership is required" }); const token = randomBytes(32).toString("base64url"); const expiresAt = new Date(Date.now() + 365 * 24 * 60 * 60_000); await db.update(podcastPrivateFeedTokens).set({ revokedAt: new Date() }).where(and(eq(podcastPrivateFeedTokens.showId, show.id), eq(podcastPrivateFeedTokens.userId, req.dbUser!.id), isNull(podcastPrivateFeedTokens.revokedAt))); await db.insert(podcastPrivateFeedTokens).values({ showId: show.id, userId: req.dbUser!.id, tokenHash: tokenHash(token), expiresAt }); return res.status(201).json({ feedUrl: `${appUrl()}/api/podcasts/feed/${show.publicId}/${token}.xml`, expiresAt }); });

  app.get("/api/podcasts/feed/:publicId.xml", async (req, res) => { const [show] = await db.select().from(podcastShows).where(and(eq(podcastShows.publicId, req.params.publicId), eq(podcastShows.status, "published"))).limit(1); if (!show) return res.status(404).send("Feed not found"); if (show.redirectUrl) return res.redirect(301, show.redirectUrl); if (show.access !== "public") return res.status(404).send("Feed not found"); res.type("application/rss+xml"); res.setHeader("Cache-Control", "public, max-age=300"); return res.send(await feedXml(show)); });
  app.get("/api/podcasts/feed/:publicId/:token.xml", async (req, res) => { const [show] = await db.select().from(podcastShows).where(and(eq(podcastShows.publicId, req.params.publicId), eq(podcastShows.status, "published"))).limit(1); if (!show || !await validFeedToken(show.id, req.params.token)) return res.status(404).send("Feed not found"); res.type("application/rss+xml"); res.setHeader("Cache-Control", "private, no-store"); return res.send(await feedXml(show, req.params.token)); });
  app.get("/api/podcasts/episodes/:publicId/media", async (req, res) => { const [row] = await db.select({ episode: podcastEpisodes, show: podcastShows, media: assets }).from(podcastEpisodes).innerJoin(podcastShows, eq(podcastEpisodes.showId, podcastShows.id)).innerJoin(assets, eq(podcastEpisodes.mediaAssetId, assets.id)).where(and(eq(podcastEpisodes.publicId, req.params.publicId), eq(podcastEpisodes.status, "published"), eq(podcastShows.status, "published"))).limit(1); if (!row) return res.status(404).send("Episode not found"); const effectiveAccess = row.episode.access === "show_default" ? row.show.access : row.episode.access; if (effectiveAccess !== "public" && !(typeof req.query.token === "string" && await validFeedToken(row.show.id, req.query.token))) return res.status(404).send("Episode not found"); const target = row.media.publicUrl ?? (row.media.storageProvider === "local" && process.env.NODE_ENV !== "production" ? null : (await createPrivateAssetReadUrl(row.media.storageKey)).url); if (!target) return res.status(503).send("Media delivery unavailable"); return res.redirect(302, target); });
  app.get("/api/podcasts/episodes/:publicId/chapters.json", async (req, res) => { const [row] = await db.select({ episode: podcastEpisodes, show: podcastShows }).from(podcastEpisodes).innerJoin(podcastShows, eq(podcastEpisodes.showId, podcastShows.id)).where(and(eq(podcastEpisodes.publicId, req.params.publicId), eq(podcastEpisodes.status, "published"))).limit(1); if (!row) return res.status(404).json({ message: "Episode not found" }); const effectiveAccess = row.episode.access === "show_default" ? row.show.access : row.episode.access; if (effectiveAccess !== "public" && !(typeof req.query.token === "string" && await validFeedToken(row.show.id, req.query.token))) return res.status(404).json({ message: "Episode not found" }); return res.json({ version: "1.2.0", chapters: row.episode.chapters.map((chapter) => ({ startTime: chapter.startSeconds, title: chapter.title, url: chapter.url })) }); });

  app.post("/api/podcasts/:id/private-feed", attachUser, async (req, res) => { const show = await ownedShow(req.dbUser!.id, req.params.id); const userId = Number.isInteger(req.body?.userId) ? req.body.userId : req.dbUser!.id; if (!show) return res.status(404).json({ message: "Show not found" }); if (!await userCanAccessShow(userId, show)) return res.status(403).json({ message: "User lacks an active show entitlement" }); const token = randomBytes(32).toString("base64url"); const expiresAt = new Date(Date.now() + 365 * 24 * 60 * 60_000); await db.insert(podcastPrivateFeedTokens).values({ showId: show.id, userId, tokenHash: tokenHash(token), expiresAt }); return res.status(201).json({ feedUrl: `${appUrl()}/api/podcasts/feed/${show.publicId}/${token}.xml`, expiresAt }); });
  app.post("/api/podcasts/:id/destinations", attachUser, async (req, res) => { const show = await ownedShow(req.dbUser!.id, req.params.id); const provider = typeof req.body?.provider === "string" ? req.body.provider.trim().toLowerCase().slice(0, 80) : ""; if (!show || !provider) return res.status(show ? 400 : 404).json({ message: show ? "Provider is required" : "Show not found" }); const [destination] = await db.insert(podcastDestinations).values({ showId: show.id, provider, feedUrl: `${appUrl()}/api/podcasts/feed/${show.publicId}.xml`, status: "pending", errorCode: "provider_unconfigured", errorMessage: "Connect and verify the directory provider to activate this destination" }).onConflictDoUpdate({ target: [podcastDestinations.showId, podcastDestinations.provider], set: { feedUrl: `${appUrl()}/api/podcasts/feed/${show.publicId}.xml`, updatedAt: new Date() } }).returning(); return res.status(201).json(destination); });

  app.post("/api/podcasts/import", attachUser, async (req, res) => { const sourceUrl = typeof req.body?.sourceUrl === "string" ? req.body.sourceUrl.trim() : ""; const sourceXml = typeof req.body?.rssXml === "string" ? req.body.rssXml : ""; if (!sourceUrl || !sourceXml || req.body?.confirmRights !== true) return res.status(400).json({ message: "Source URL, RSS XML, and rights confirmation are required" }); let url: URL; try { url = new URL(sourceUrl); if (!['http:', 'https:'].includes(url.protocol)) throw new Error(); } catch { return res.status(400).json({ message: "Valid source URL required" }); } const items = importedItems(sourceXml).filter((item) => /^https?:\/\//.test(item.enclosure)); if (!items.length) return res.status(400).json({ message: "RSS contains no importable enclosure items" }); const title = (sourceXml.match(/<channel>[\s\S]*?<title>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/i)?.[1] ?? `Imported show ${Date.now()}`).trim(); const business = await businessFor(req.dbUser!.id); const result = await db.transaction(async (tx) => { const [show] = await tx.insert(podcastShows).values({ businessId: business.id, ownerUserId: req.dbUser!.id, publicId: id("show"), title, description: "Imported podcast", author: req.dbUser!.displayName, ownerEmail: req.dbUser!.authEmail ?? "podcast-owner@creativesos.net", importedFromUrl: url.toString(), status: "draft" }).returning(); const created = []; for (let index = 0; index < items.length; index += 1) { const item = items[index]; const [asset] = await tx.insert(assets).values({ ownerUserId: req.dbUser!.id, businessId: business.id, kind: item.mimeType.startsWith("video/") ? "video" : "audio", storageProvider: "remote-import", storageKey: item.enclosure, publicUrl: item.enclosure, mimeType: item.mimeType, visibility: "public", status: "ready", originalFilename: `imported-${index + 1}`, metadata: { sourceUrl: url.toString(), rightsConfirmedByUserId: req.dbUser!.id } }).returning(); const [episode] = await tx.insert(podcastEpisodes).values({ showId: show.id, createdByUserId: req.dbUser!.id, publicId: id("episode"), title: item.title, description: item.description, episodeNumber: index + 1, mediaAssetId: asset.id, status: "draft", publishedAt: item.publishedAt }).returning(); created.push(episode); } return { show, episodes: created }; }); return res.status(201).json(result); });

  app.post("/api/podcasts/episodes/:id/comments", attachUser, async (req, res) => { const row = await episodeWithShow(req.params.id); const body = typeof req.body?.body === "string" ? req.body.body.trim().slice(0, 5_000) : ""; if (!row || row.episode.status !== "published" || !await userCanAccessShow(req.dbUser!.id, row.show)) return res.status(404).json({ message: "Episode not found" }); if (!body) return res.status(400).json({ message: "Comment is required" }); const parentId = typeof req.body?.parentId === "string" ? req.body.parentId : null; if (parentId) { const [parent] = await db.select().from(podcastEpisodeComments).where(and(eq(podcastEpisodeComments.id, parentId), eq(podcastEpisodeComments.episodeId, row.episode.id))).limit(1); if (!parent) return res.status(404).json({ message: "Parent comment not found" }); } const [comment] = await db.insert(podcastEpisodeComments).values({ episodeId: row.episode.id, userId: req.dbUser!.id, parentId, body }).returning(); return res.status(201).json(comment); });
  app.get("/api/podcasts/episodes/:id/community", attachUser, async (req, res) => { const row = await episodeWithShow(req.params.id); if (!row || row.episode.status !== "published" || !await userCanAccessShow(req.dbUser!.id, row.show)) return res.status(404).json({ message: "Episode not found" }); const [comments, poll] = await Promise.all([db.select({ id: podcastEpisodeComments.id, parentId: podcastEpisodeComments.parentId, body: podcastEpisodeComments.body, status: podcastEpisodeComments.status, createdAt: podcastEpisodeComments.createdAt, user: users.displayName }).from(podcastEpisodeComments).innerJoin(users, eq(podcastEpisodeComments.userId, users.id)).where(and(eq(podcastEpisodeComments.episodeId, row.episode.id), eq(podcastEpisodeComments.status, "visible"))).orderBy(asc(podcastEpisodeComments.createdAt)), db.select().from(podcastPolls).where(eq(podcastPolls.episodeId, row.episode.id)).limit(1)]); const votes = poll[0] ? await db.select({ optionId: podcastPollVotes.optionId, count: sql<number>`count(*)::int` }).from(podcastPollVotes).where(eq(podcastPollVotes.pollId, poll[0].id)).groupBy(podcastPollVotes.optionId) : []; return res.json({ comments, poll: poll[0] ? { ...poll[0], votes } : null }); });
  app.get("/api/public/podcasts/episodes/:publicId/community", async (req, res) => { const [row] = await db.select({ episode: podcastEpisodes, show: podcastShows }).from(podcastEpisodes).innerJoin(podcastShows, eq(podcastEpisodes.showId, podcastShows.id)).where(and(eq(podcastEpisodes.publicId, req.params.publicId), eq(podcastEpisodes.status, "published"), eq(podcastShows.status, "published"), eq(podcastShows.access, "public"), inArray(podcastEpisodes.access, ["show_default", "public"]))).limit(1); if (!row) return res.status(404).json({ message: "Episode not found" }); const [comments, poll] = await Promise.all([db.select({ id: podcastEpisodeComments.id, parentId: podcastEpisodeComments.parentId, body: podcastEpisodeComments.body, createdAt: podcastEpisodeComments.createdAt, user: users.displayName }).from(podcastEpisodeComments).innerJoin(users, eq(podcastEpisodeComments.userId, users.id)).where(and(eq(podcastEpisodeComments.episodeId, row.episode.id), eq(podcastEpisodeComments.status, "visible"))).orderBy(asc(podcastEpisodeComments.createdAt)), db.select().from(podcastPolls).where(eq(podcastPolls.episodeId, row.episode.id)).limit(1)]); const votes = poll[0] ? await db.select({ optionId: podcastPollVotes.optionId, count: sql<number>`count(*)::int` }).from(podcastPollVotes).where(eq(podcastPollVotes.pollId, poll[0].id)).groupBy(podcastPollVotes.optionId) : []; return res.json({ comments, poll: poll[0] ? { ...poll[0], votes } : null }); });
  app.post("/api/podcasts/episodes/:id/poll", attachUser, async (req, res) => { const parsed = podcastPollSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid poll" }); const row = await episodeWithShow(req.params.id); if (!row || !await userCanManageBusiness(req.dbUser!.id, row.show.businessId)) return res.status(404).json({ message: "Episode not found" }); const [poll] = await db.insert(podcastPolls).values({ episodeId: row.episode.id, ...parsed.data }).returning(); return res.status(201).json(poll); });
  app.post("/api/podcasts/polls/:id/vote", attachUser, async (req, res) => { const [poll] = await db.select().from(podcastPolls).where(eq(podcastPolls.id, req.params.id)).limit(1); const optionId = typeof req.body?.optionId === "string" ? req.body.optionId : ""; if (!poll || poll.status !== "open" || (poll.closesAt && poll.closesAt <= new Date())) return res.status(409).json({ message: "Poll is closed" }); if (!poll.options.some((option) => option.id === optionId)) return res.status(400).json({ message: "Invalid option" }); const [vote] = await db.insert(podcastPollVotes).values({ pollId: poll.id, userId: req.dbUser!.id, optionId }).onConflictDoUpdate({ target: [podcastPollVotes.pollId, podcastPollVotes.userId], set: { optionId } }).returning(); return res.json(vote); });
  app.post("/api/podcasts/episodes/:id/playback", attachUser, async (req, res) => { const row = await episodeWithShow(req.params.id); if (!row || row.episode.status !== "published" || !await userCanAccessShow(req.dbUser!.id, row.show)) return res.status(404).json({ message: "Episode not found" }); if (req.body?.consentState !== "analytics") return res.status(202).json({ accepted: false, status: "suppressed" }); return res.status(202).json({ accepted: await recordPlayback({ row, userId: req.dbUser!.id, body: req.body }) }); });
  app.post("/api/public/podcasts/episodes/:publicId/playback", async (req, res) => { const [row] = await db.select({ episode: podcastEpisodes, show: podcastShows }).from(podcastEpisodes).innerJoin(podcastShows, eq(podcastEpisodes.showId, podcastShows.id)).where(and(eq(podcastEpisodes.publicId, req.params.publicId), eq(podcastEpisodes.status, "published"), eq(podcastShows.status, "published"), eq(podcastShows.access, "public"), inArray(podcastEpisodes.access, ["show_default", "public"]))).limit(1); if (!row) return res.status(404).json({ message: "Episode not found" }); if (req.body?.consentState !== "analytics") return res.status(202).json({ accepted: false, status: "suppressed" }); const anonymousId = createHash("sha256").update(String(req.body?.anonymousId ?? playbackInput(req.body).sessionId)).digest("hex").slice(0, 32); return res.status(202).json({ accepted: await recordPlayback({ row, anonymousId, body: req.body }) }); });
  app.get("/api/podcasts/:id/analytics", attachUser, async (req, res) => { const show = await ownedShow(req.dbUser!.id, req.params.id); if (!show) return res.status(404).json({ message: "Show not found" }); const episodes = await db.select().from(podcastEpisodes).where(eq(podcastEpisodes.showId, show.id)); const ids = episodes.map((episode) => episode.id); const events = ids.length ? await db.select({ objectId: analyticsEvents.objectId, eventName: analyticsEvents.eventName, count: sql<number>`count(*)::int`, listeners: sql<number>`count(distinct coalesce(${analyticsEvents.userId}::text, ${analyticsEvents.anonymousId}))::int` }).from(analyticsEvents).where(and(inArray(analyticsEvents.objectId, ids), inArray(analyticsEvents.eventName, ["podcast.start", "podcast.progress", "podcast.complete"]))).groupBy(analyticsEvents.objectId, analyticsEvents.eventName) : []; return res.json({ showId: show.id, episodes: episodes.map((episode) => { const rows = events.filter((event) => event.objectId === episode.id); const value = (name: string) => rows.find((event) => event.eventName === name)?.count ?? 0; return { id: episode.id, title: episode.title, starts: value("podcast.start"), progressEvents: value("podcast.progress"), completes: value("podcast.complete"), listeners: Math.max(0, ...rows.map((event) => event.listeners)) }; }) }); });
}
