import type { Express } from "express";
import { and, desc, eq } from "drizzle-orm";
import { decideRightsCaseSchema, provenanceClaimSchema, submitRightsCaseSchema } from "@shared/trust";
import { assetProvenanceClaims, assetRights, assetUsageRecords, assets, repeatInfringerStrikes, rightsCaseEvents, rightsCases } from "@shared/schema";
import { attachUser } from "./auth";
import { db } from "./db";

async function ownedAsset(userId: number, id: string) { const [asset] = await db.select().from(assets).where(and(eq(assets.id, id), eq(assets.ownerUserId, userId))).limit(1); return asset ?? null; }

export function registerTrustRoutes(app: Express) {
  app.get("/api/trust/assets/:id/provenance", attachUser, async (req, res) => { const asset = await ownedAsset(req.dbUser!.id, req.params.id); if (!asset) return res.status(404).json({ message: "Asset not found" }); return res.json(await db.select().from(assetProvenanceClaims).where(eq(assetProvenanceClaims.assetId, asset.id)).orderBy(desc(assetProvenanceClaims.createdAt))); });
  app.post("/api/trust/assets/:id/provenance", attachUser, async (req, res) => { const parsed = provenanceClaimSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid provenance claim" }); const asset = await ownedAsset(req.dbUser!.id, req.params.id); if (!asset) return res.status(404).json({ message: "Asset not found" }); for (const sourceId of parsed.data.sourceAssetIds) if (!await ownedAsset(req.dbUser!.id, sourceId)) return res.status(404).json({ message: "Every source asset must belong to you" }); const [claim] = await db.insert(assetProvenanceClaims).values({ assetId: asset.id, assertedByUserId: req.dbUser!.id, ...parsed.data }).returning(); if (["ai_generated", "synthetic_media", "cloned_voice"].includes(claim.kind)) await db.update(assetRights).set({ syntheticMedia: true, clonedVoice: claim.kind === "cloned_voice", updatedAt: new Date() }).where(eq(assetRights.assetId, asset.id)); return res.status(201).json(claim); });

  app.post("/api/trust/rights-cases", attachUser, async (req, res) => {
    const parsed = submitRightsCaseSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid rights case" }); if (parsed.data.assetId) { const [asset] = await db.select().from(assets).where(eq(assets.id, parsed.data.assetId)).limit(1); if (!asset) return res.status(404).json({ message: "Referenced asset not found" }); }
    let parent = null; if (parsed.data.parentCaseId) { [parent] = await db.select().from(rightsCases).where(eq(rightsCases.id, parsed.data.parentCaseId)).limit(1); if (!parent) return res.status(404).json({ message: "Parent case not found" }); if (parsed.data.caseType === "takedown") return res.status(409).json({ message: "A takedown starts a new case" }); }
    const dueDays = parsed.data.caseType === "counter_notice" ? 10 : 14; const [created] = await db.insert(rightsCases).values({ ...parsed.data, submittedByUserId: req.dbUser!.id, dueAt: new Date(Date.now() + dueDays * 86_400_000) }).returning(); await db.insert(rightsCaseEvents).values({ caseId: created.id, actorUserId: req.dbUser!.id, eventType: `${created.caseType}.submitted`, note: "Case submitted with claimant attestation", evidence: { evidenceCount: created.evidence.length } }); if (parent) { const parentStatus = created.caseType === "counter_notice" ? "countered" : "appealed"; await db.update(rightsCases).set({ status: parentStatus, updatedAt: new Date() }).where(eq(rightsCases.id, parent.id)); await db.insert(rightsCaseEvents).values({ caseId: parent.id, actorUserId: req.dbUser!.id, eventType: `${created.caseType}.received`, note: `Linked case ${created.id}` }); } return res.status(201).json(created);
  });

  app.get("/api/trust/rights-cases", attachUser, async (req, res) => { const rows = req.dbUser!.role === "admin" ? await db.select().from(rightsCases).orderBy(desc(rightsCases.submittedAt)).limit(1_000) : await db.select().from(rightsCases).where(eq(rightsCases.submittedByUserId, req.dbUser!.id)).orderBy(desc(rightsCases.submittedAt)).limit(500); return res.json(rows); });
  app.get("/api/trust/rights-cases/:id", attachUser, async (req, res) => { const [caseRow] = await db.select().from(rightsCases).where(eq(rightsCases.id, req.params.id)).limit(1); if (!caseRow || (req.dbUser!.role !== "admin" && caseRow.submittedByUserId !== req.dbUser!.id)) return res.status(404).json({ message: "Case not found" }); const events = await db.select().from(rightsCaseEvents).where(eq(rightsCaseEvents.caseId, caseRow.id)).orderBy(rightsCaseEvents.createdAt); return res.json({ ...caseRow, events }); });
  app.post("/api/trust/rights-cases/:id/decision", attachUser, async (req, res) => { if (req.dbUser!.role !== "admin") return res.status(403).json({ message: "Administrator access required" }); const parsed = decideRightsCaseSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message ?? "Invalid case decision" }); const [caseRow] = await db.select().from(rightsCases).where(eq(rightsCases.id, req.params.id)).limit(1); if (!caseRow) return res.status(404).json({ message: "Case not found" }); const now = new Date(); const [updated] = await db.update(rightsCases).set({ status: parsed.data.status, decision: parsed.data.decision, assignedReviewerUserId: req.dbUser!.id, decidedAt: ["actioned", "resolved", "rejected", "withdrawn"].includes(parsed.data.status) ? now : null, updatedAt: now }).where(eq(rightsCases.id, caseRow.id)).returning(); await db.insert(rightsCaseEvents).values({ caseId: caseRow.id, actorUserId: req.dbUser!.id, eventType: `case.${parsed.data.status}`, note: parsed.data.decision }); if (caseRow.assetId && parsed.data.status === "actioned") { await db.update(assetRights).set({ status: "disputed", updatedAt: now }).where(eq(assetRights.assetId, caseRow.assetId)); await db.update(assetUsageRecords).set({ state: "blocked", endedAt: now, updatedAt: now }).where(and(eq(assetUsageRecords.assetId, caseRow.assetId), eq(assetUsageRecords.state, "active"))); } if (parsed.data.issueStrikeToUserId && ["actioned", "resolved"].includes(parsed.data.status)) await db.insert(repeatInfringerStrikes).values({ userId: parsed.data.issueStrikeToUserId, caseId: caseRow.id, reason: parsed.data.decision, issuedByUserId: req.dbUser!.id }).onConflictDoNothing(); return res.json(updated); });
  app.post("/api/trust/strikes/:id/reverse", attachUser, async (req, res) => { if (req.dbUser!.role !== "admin") return res.status(403).json({ message: "Administrator access required" }); const [strike] = await db.update(repeatInfringerStrikes).set({ status: "reversed", reversedAt: new Date() }).where(and(eq(repeatInfringerStrikes.id, req.params.id), eq(repeatInfringerStrikes.status, "active"))).returning(); if (!strike) return res.status(404).json({ message: "Active strike not found" }); await db.insert(rightsCaseEvents).values({ caseId: strike.caseId, actorUserId: req.dbUser!.id, eventType: "strike.reversed", note: typeof req.body?.reason === "string" ? req.body.reason.slice(0, 2_000) : "Reversed after review" }); return res.json(strike); });
}
