import { expect, test, type APIResponse, type Page, type TestInfo } from "@playwright/test";
function actors(testInfo: TestInfo) { const owner = testInfo.project.name.startsWith("mobile") ? 1 : 2; return { owner, partner: owner === 1 ? 2 : 1, buyer: 4 }; }
async function api(page: Page, actor: number, method: string, url: string, data?: unknown) { return page.request.fetch(url,{method,data,headers:{"x-creativesos-demo-user":String(actor)}}); }
async function ok(response: APIResponse) { expect(response.ok(),`${response.status()} ${response.url()}: ${await response.text()}`).toBeTruthy(); }
test("affiliate program carries application, consented click, commerce attribution, commission, reversal, and provider-gated payout", async ({ page }, testInfo) => {
  const { owner, partner, buyer } = actors(testInfo); const stamp = `${testInfo.project.name}-${Date.now()}`;
  const productsResponse = await api(page,owner,"GET","/api/products"); await ok(productsResponse); const products = await productsResponse.json() as Array<{id:number;userId:number;title:string}>; const product = products.find((item)=>item.userId===owner)!;
  const programResponse = await api(page,owner,"POST","/api/affiliates/programs",{name:`Partner engine ${stamp}`,slug:`partners-${stamp.toLowerCase()}`,description:"Governed partner growth",applicationMode:"review",attributionModel:"last_click",attributionWindowDays:30,cookieConsentRequired:true,productIds:[product.id],commissionRule:{type:"percentage",commissionBps:2000,fixedAmountCents:0,recurringCycles:3,newCustomersOnly:false},holdDays:0,minimumPayoutCents:1,currency:"usd"}); await ok(programResponse); const program = await programResponse.json();
  await ok(await api(page,owner,"PATCH",`/api/affiliates/programs/${program.id}/status`,{status:"active"}));
  const applicationResponse = await api(page,partner,"POST",`/api/affiliates/programs/${program.id}/apply`,{displayName:`Partner ${stamp}`,email:`partner-${stamp}@example.com`,partnerType:"community_ambassador",audienceSummary:"Qualified community",promotionPlan:"Owned newsletter and community"}); await ok(applicationResponse); const application = await applicationResponse.json();
  const approvalResponse = await api(page,owner,"PATCH",`/api/affiliates/applications/${application.id}`,{status:"approved",note:"Approved after review"}); await ok(approvalResponse); const approved = await approvalResponse.json(); const partnerRow = approved.partner;
  const linkResponse = await api(page,owner,"POST",`/api/affiliates/partners/${partnerRow.id}/links`,{name:"Marketplace referral",destinationUrl:`/marketplace/product/${product.id}`}); await ok(linkResponse); const link = await linkResponse.json();
  await page.goto(`${new URL(link.referralUrl).pathname}?consent=granted`); await expect(page).toHaveURL(new RegExp(`/marketplace/product/${product.id}`));
  const orderResponse = await api(page,buyer,"POST","/api/orders",{productIds:[product.id],idempotencyKey:`affiliate-order-${stamp}`}); await ok(orderResponse); const order = await orderResponse.json(); expect(order.attributionContext.affiliatePartnerId).toBe(partnerRow.id); expect(order.attributionContext.affiliateSelfReferral).toBe(false);
  await ok(await api(page,buyer,"POST",`/api/qualification/orders/${order.id}/settle`,{providerReference:`qualified-${stamp}`}));
  await ok(await api(page,buyer,"POST",`/api/qualification/orders/${order.id}/settle`,{providerReference:`qualified-${stamp}`}));
  let dashboardResponse = await api(page,owner,"GET","/api/affiliates"); await ok(dashboardResponse); let dashboard = await dashboardResponse.json(); expect(dashboard.conversions).toHaveLength(1); const conversion = dashboard.conversions[0]; expect(conversion.commissionCents).toBe(Math.floor(Math.round(order.totalAmount*100)*0.2));
  await ok(await api(page,owner,"POST",`/api/affiliates/programs/${program.id}/reconcile`,{}));
  await ok(await api(page,owner,"POST",`/api/affiliates/conversions/${conversion.id}/reverse`,{amountCents:100,sourceReference:`partial-refund-${stamp}`}));
  const payoutResponse = await api(page,owner,"POST",`/api/affiliates/partners/${partnerRow.id}/payouts`,{}); await ok(payoutResponse); expect((await payoutResponse.json()).providerStatus).toBe("provider_pending");
  dashboardResponse = await api(page,owner,"GET","/api/affiliates"); dashboard = await dashboardResponse.json(); expect(dashboard.conversions[0].status).toBe("partially_reversed"); expect(dashboard.payouts[0].status).toBe("provider_pending"); expect(dashboard.leaderboard[0].partner.partnerType).toBe("community_ambassador");
  await page.goto("/business/affiliates"); await expect(page.getByRole("heading",{name:"Affiliate & Referral Studio"})).toBeVisible(); await expect(page.getByText(`Partner engine ${stamp}`,{exact:true})).toBeVisible(); await expect(page.getByText(/provider_pending/)).toBeVisible();
  await page.goto(`/affiliates/${program.slug}`); await expect(page.getByRole("heading",{name:`Partner engine ${stamp}`})).toBeVisible(); await expect(page.getByRole("heading",{name:"Community leaderboard"})).toBeVisible(); await expect(page.getByText(`Partner ${stamp}`,{exact:true})).toBeVisible();
});
