import { expect, test } from "@playwright/test";
test.setTimeout(120_000);
test("Creator Site owns public sections, capture, redirects, domains, and consent-aware conversion evidence", async ({ page }, testInfo) => {
  const stamp = `${testInfo.project.name}-${Date.now()}`.toLowerCase(); const slug = `site-${stamp.replace(/[^a-z0-9-]/g, "-")}`.slice(0, 60);
  const formResponse = await page.request.post("/api/audience/forms", { data: { name: `Site form ${stamp}`, title: "Join the owned audience", description: "Updates", fields: [], tags: ["site"], consentPurpose: "marketing", disclosureVersion: "site-v1", successMessage: "Welcome to the owned audience." } }); expect(formResponse.status()).toBe(201); const form = await formResponse.json() as { id: string; publicId: string }; expect((await page.request.post(`/api/audience/forms/${form.id}/publish`)).status()).toBe(200);
  const theme = { background: "#000000", surface: "#09090b", text: "#ffffff", muted: "#71717a", accent: "#1d9bf0", radius: "large", font: "sans" };
  const siteResponse = await page.request.post("/api/sites", { data: { slug, name: `Owned ${stamp}`, tagline: "Build, distribute, own", bio: "The creator operating destination", avatarAssetId: null, theme, seo: { title: `Owned ${stamp}`.slice(0,70), description: "A qualified creator destination", imageAssetId: null, noIndex: false } } }); expect(siteResponse.status()).toBe(201); const site = await siteResponse.json() as { id: string };
  const hero = await page.request.post(`/api/sites/${site.id}/sections`, { data: { name: "Hero", payload: { type: "hero", eyebrow: "Creator-owned", heading: "Make the relationship durable", body: "One destination for the audience and offer.", ctaLabel: "Explore", ctaUrl: "/marketplace" }, sortOrder: 0, visibility: "public" } }); expect(hero.status()).toBe(201);
  expect((await page.request.post(`/api/sites/${site.id}/sections`, { data: { name: "Links", payload: { type: "links", heading: "Start here", links: [{ id: "offer", label: "Marketplace", url: "/marketplace", description: "Browse", featured: true }] }, sortOrder: 1, visibility: "public" } })).status()).toBe(201);
  expect((await page.request.post(`/api/sites/${site.id}/sections`, { data: { name: "Subscribe", payload: { type: "subscribe", heading: "Join us", body: "Get the next release", formPublicId: form.publicId }, sortOrder: 2, visibility: "public" } })).status()).toBe(201);
  const unsafe = await page.request.post(`/api/sites/${site.id}/sections`, { data: { name: "Unsafe", payload: { type: "links", heading: "No", links: [{ id: "bad", label: "Bad", url: "javascript:alert(1)", description: "", featured: false }] }, sortOrder: 3, visibility: "public" } }); expect(unsafe.status()).toBe(400);
  expect((await page.request.post(`/api/sites/${site.id}/redirects`, { data: { sourcePath: "/start", targetUrl: "/marketplace", statusCode: 302 } })).status()).toBe(201);
  const domain = await page.request.post(`/api/sites/${site.id}/domains`, { data: { domain: `${slug}.example.com` } }); expect(domain.status()).toBe(201); const domainData = await domain.json(); expect(domainData.dns.name).toBe(`_creativesos.${slug}.example.com`); expect(domainData.dns.value).toContain("creativesos-site-verification=");
  expect((await page.request.post(`/api/sites/${site.id}/publish`)).status()).toBe(200);
  const publicResponse = await page.request.get(`/api/public/sites/${slug}`); expect(publicResponse.status()).toBe(200); const publicData = await publicResponse.json(); expect(publicData.sections).toHaveLength(3); expect(publicData.site.seo.title).toContain("Owned");
  const suppressed = await page.request.post(`/api/public/sites/${slug}/events`, { data: { event: "view", sessionId: `${stamp}-session`, anonymousId: stamp, sequence: 1 } }); expect((await suppressed.json()).status).toBe("suppressed");
  for (const [event, sequence] of [["view",2],["click",3],["subscribe",4]] as const) { const tracked = await page.request.post(`/api/public/sites/${slug}/events`, { data: { event, sessionId: `${stamp}-session`, anonymousId: stamp, sequence, consentState: "analytics", sectionId: "qualification" } }); expect(tracked.status()).toBe(202); expect((await tracked.json()).accepted).toBe(true); }
  const capture = await page.request.post(`/api/public/audience/forms/${form.publicId}/submissions`, { data: { email: `${stamp}@example.com`, values: {}, consentGranted: true } }); expect(capture.status()).toBe(201);
  const redirect = await page.request.get(`/api/public/sites/${slug}/go/start`, { maxRedirects: 0 }); expect(redirect.status()).toBe(302); expect(redirect.headers().location).toBe("/marketplace");
  const owner = await page.request.get("/api/sites"); const ownerData = await owner.json(); expect(ownerData.metrics.find((item: { eventName: string }) => item.eventName === "site.view").count).toBe(1); expect(ownerData.redirects[0].hits).toBe(1);
  await page.goto("/business/site"); await expect(page.getByRole("heading", { name: "Creator Site & Link Hub" })).toBeVisible(); await expect(page.getByText(`Owned ${stamp}`)).toBeVisible(); await page.goto(`/s/${slug}`); await expect(page.getByRole("heading", { name: "Make the relationship durable" })).toBeVisible(); await expect(page.getByText("Start here")).toBeVisible(); await expect(page.getByRole("button", { name: "Join" })).toBeVisible();
});
