import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { expect, test, type APIResponse, type Page, type TestInfo } from "@playwright/test";

function ownerFor(testInfo: TestInfo) { return testInfo.project.name.startsWith("mobile") ? 1 : 2; }
async function request(page: Page, owner: number, method: string, url: string, data?: unknown, headers: Record<string, string> = {}) { return page.request.fetch(url, { method, data, headers: { "x-creativesos-demo-user": String(owner), ...headers } }); }
async function expectOk(response: APIResponse) { expect(response.ok(), `${response.status()} ${response.url()}: ${await response.text()}`).toBeTruthy(); }

test("CutStudio persists and enforces the programmable motion and cinematic production lifecycle", async ({ page }, testInfo) => {
  test.setTimeout(180_000);
  const owner = ownerFor(testInfo);
  const peer = owner === 1 ? 2 : 1;
  const peerUsername = peer === 1 ? "owner" : "sarahmitchell";
  const directory = testInfo.outputPath("programmable-cinema");
  mkdirSync(directory, { recursive: true });
  const sourcePath = `${directory}/source.mp4`;
  const imagePath = `${directory}/product-still.png`;
  const maskPath = `${directory}/half-mask.png`;
  const fontPath = ["C:/Windows/Fonts/times.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf"].find(existsSync);
  expect(fontPath, "A system TTF is required for the private-font render proof").toBeTruthy();
  execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", "color=c=black:size=640x360:rate=30:duration=2", "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=2", "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", sourcePath]);
  execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", "color=c=magenta:size=200x100", "-frames:v", "1", imagePath]);
  execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", "color=c=black:size=200x100", "-vf", "drawbox=x=100:y=0:w=100:h=100:color=white:t=fill", "-frames:v", "1", maskPath]);
  const upload = await page.request.post("/api/assets/upload-proxy", { headers: { "x-creativesos-demo-user": String(owner) }, multipart: { kind: "video", visibility: "private", video: { name: "source.mp4", mimeType: "video/mp4", buffer: readFileSync(sourcePath) } } });
  await expectOk(upload);
  const source = (await upload.json()).asset;
  const created = await request(page, owner, "POST", "/api/cut/projects", { sourceAssetId: source.id, name: `Programmable cinema ${Date.now()}`, duration: 2, mediaKind: "video" });
  await expectOk(created);
  const project = await created.json();
  const imageUpload = await page.request.post("/api/assets/upload-proxy", { headers: { "x-creativesos-demo-user": String(owner) }, multipart: { kind: "photo", visibility: "private", image: { name: "product-still.png", mimeType: "image/png", buffer: readFileSync(imagePath) } } });
  await expectOk(imageUpload);
  const imageAsset = (await imageUpload.json()).asset;
  await expectOk(await request(page, owner, "POST", `/api/cut/projects/${project.id}/media-library`, { assetId: imageAsset.id, name: "Product still", duration: 2, mediaKind: "image" }));
  const maskUpload = await page.request.post("/api/assets/upload-proxy", { headers: { "x-creativesos-demo-user": String(owner) }, multipart: { kind: "photo", visibility: "private", image: { name: "half-mask.png", mimeType: "image/png", buffer: readFileSync(maskPath) } } });
  await expectOk(maskUpload);
  const maskAsset = (await maskUpload.json()).asset;
  await expectOk(await request(page, owner, "POST", `/api/cut/projects/${project.id}/media-library`, { assetId: maskAsset.id, name: "Half mask", duration: 2, mediaKind: "image" }));
  const fontUpload = await page.request.post("/api/assets/upload-proxy", { headers: { "x-creativesos-demo-user": String(owner) }, multipart: { kind: "cut-font", visibility: "private", font: { name: "EditorialSerif.ttf", mimeType: "font/ttf", buffer: readFileSync(fontPath!) } } });
  await expectOk(fontUpload);
  const fontAsset = (await fontUpload.json()).asset;
  await expectOk(await request(page, owner, "POST", `/api/cut/projects/${project.id}/media-library`, { assetId: fontAsset.id, name: "Editorial Serif", duration: 2, mediaKind: "font" }));
  expect((await request(page, peer, "GET", `/api/cut/projects/${project.id}/creative-runtime`)).status()).toBe(404);

  await page.goto(`/cut-studio?project=${project.id}`);
  await expect(page.getByRole("heading", { name: project.name })).toBeVisible();
  const studio = page.getByLabel("CutStudio creative runtime");
  await expect(studio.getByText("Motion graphics + cinema studio")).toBeVisible();
  await studio.getByRole("button", { name: "Kinetic" }).click();
  await expect(studio.getByText(/Motion composition saved/)).toBeVisible();
  await expect(studio.getByLabel("Deterministic composition preview")).toBeVisible();
  await studio.getByLabel("Preview frame").fill("30");
  await expect(studio.getByText(/Frame 31 \/ /)).toBeVisible();
  await studio.getByLabel("Layer content").fill("A connected creative system");
  await studio.getByLabel("New layer kind").selectOption("video");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Project B-roll");
  await expect(studio.getByLabel("Layer media asset")).toHaveValue(source.id);
  await studio.getByLabel("New layer kind").selectOption("shape");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Brand accent");
  await studio.getByLabel("Layer fill color").fill("#f43f5e");
  await studio.getByLabel("Layer rotate x").fill("-18");
  await studio.getByLabel("Layer rotate y").fill("32");
  await studio.getByLabel("Layer perspective").fill("700");
  await studio.getByLabel("enter transition", { exact: true }).selectOption("iris");
  await studio.getByLabel("enter transition frames").fill("20");
  await studio.getByLabel("Keyframe property").selectOption("opacity");
  await studio.getByLabel("Keyframe frame").fill("12");
  await studio.getByLabel("Keyframe value").fill("0.75");
  await studio.getByRole("button", { name: "Add or replace keyframe" }).click();
  await studio.getByLabel("Keyframe property").selectOption("x");
  await studio.getByLabel("Keyframe frame").fill("30");
  await studio.getByLabel("Keyframe value").fill("0.25");
  await studio.getByRole("button", { name: "Add or replace keyframe" }).click();
  await studio.getByLabel("Keyframe property").selectOption("scale");
  await studio.getByLabel("Keyframe frame").fill("45");
  await studio.getByLabel("Keyframe value").fill("1.4");
  await studio.getByRole("button", { name: "Add or replace keyframe" }).click();
  await studio.getByLabel("Keyframe property").selectOption("blur");
  await studio.getByLabel("Keyframe frame").fill("20");
  await studio.getByLabel("Keyframe value").fill("3");
  await studio.getByRole("button", { name: "Add or replace keyframe" }).click();
  await studio.getByLabel("Keyframe property").selectOption("brightness");
  await studio.getByLabel("Keyframe frame").fill("20");
  await studio.getByLabel("Keyframe value").fill("0.9");
  await studio.getByRole("button", { name: "Add or replace keyframe" }).click();
  await studio.getByLabel("Keyframe property").selectOption("saturation");
  await studio.getByLabel("Keyframe frame").fill("20");
  await studio.getByLabel("Keyframe value").fill("0.7");
  await studio.getByRole("button", { name: "Add or replace keyframe" }).click();
  await studio.getByLabel("Add layer effect").selectOption("glow");
  await studio.getByLabel("glow amount").fill("20");
  await studio.getByLabel("Add layer effect").selectOption("drop_shadow");
  await studio.getByLabel("drop_shadow amount").fill("8");
  const shapePreview = studio.getByLabel("Deterministic composition preview").locator('[data-layer-kind="shape"]');
  await expect(shapePreview).toBeVisible();
  await expect(shapePreview).toHaveCSS("filter", /drop-shadow/);
  await expect(shapePreview).toHaveCSS("transform", /matrix3d|matrix/);
  await studio.getByLabel("New layer kind").selectOption("shape");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Directional wipe accent");
  await studio.getByLabel("Layer fill color").fill("#ff8800");
  await studio.getByLabel("Layer x").fill("0.05");
  await studio.getByLabel("Layer y").fill("0.55");
  await studio.getByLabel("Layer width").fill("0.2");
  await studio.getByLabel("Layer height").fill("0.2");
  await studio.getByLabel("enter transition", { exact: true }).selectOption("wipe");
  await studio.getByLabel("enter transition frames").fill("20");
  await studio.getByLabel("enter transition direction").selectOption("right");
  await studio.getByLabel("New layer kind").selectOption("shape");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Clock wipe accent");
  await studio.getByLabel("Layer fill color").fill("#00ffff");
  await studio.getByLabel("Layer x").fill("0.75");
  await studio.getByLabel("Layer y").fill("0.55");
  await studio.getByLabel("Layer width").fill("0.2");
  await studio.getByLabel("Layer height").fill("0.2");
  await studio.getByLabel("enter transition", { exact: true }).selectOption("clock_wipe");
  await studio.getByLabel("enter transition frames").fill("20");
  await studio.getByLabel("enter transition direction").selectOption("clockwise");
  for (const [kind, amount] of [["grain", "8"], ["noise", "4"], ["vignette", "0.35"], ["color_matrix", "0.4"], ["chroma_key", "0.12"], ["displacement", "0.2"], ["motion_blur", "1.5"], ["light_leak", "0.35"]] as const) {
    await studio.getByLabel("Add layer effect").selectOption(kind);
    await studio.getByLabel(`${kind} amount`).fill(amount);
  }
  await studio.getByLabel("New layer kind").selectOption("shape");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Custom mask accent");
  await studio.getByLabel("Layer fill color").fill("#ffffff");
  await studio.getByLabel("Layer x").fill("0.4");
  await studio.getByLabel("Layer y").fill("0.8");
  await studio.getByLabel("Layer width").fill("0.2");
  await studio.getByLabel("Layer height").fill("0.15");
  await studio.getByLabel("enter transition", { exact: true }).selectOption("custom_mask");
  await studio.getByLabel("enter transition frames").fill("20");
  await studio.getByLabel("enter transition mask").selectOption(maskAsset.id);
  await studio.getByLabel("Add layer effect").selectOption("mask");
  await studio.getByLabel("mask effect asset").selectOption(maskAsset.id);
  await studio.getByLabel("New layer kind").selectOption("path");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Vector rule");
  const pathPreview = studio.getByLabel("Deterministic composition preview").locator('[data-layer-kind="path"]');
  await expect(pathPreview.locator("svg")).toBeVisible();
  await expect(pathPreview.locator("path")).toHaveAttribute("d", "M 0 50 L 100 50");
  await studio.getByLabel("New layer kind").selectOption("svg");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Safe vector logo");
  await studio.getByLabel("Layer content").fill('<svg viewBox="0 0 100 100"><rect x="5" y="5" width="90" height="90" rx="12" fill="#00ff00"/></svg>');
  await studio.getByLabel("Layer x").fill("0.05");
  await studio.getByLabel("Layer y").fill("0.05");
  const svgPreview = studio.getByLabel("Deterministic composition preview").locator('[data-layer-kind="svg"]');
  await expect(svgPreview.locator("img")).toHaveAttribute("src", /^data:image\/svg\+xml/);
  await studio.getByLabel("New layer kind").selectOption("image");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Product still layer");
  await expect(studio.getByLabel("Layer media asset")).toHaveValue(imageAsset.id);
  await studio.getByLabel("Layer x").fill("0.7");
  await studio.getByLabel("Layer y").fill("0.05");
  await studio.getByLabel("Layer width").fill("0.2");
  await studio.getByLabel("Layer height").fill("0.2");
  await expect(studio.getByLabel("Deterministic composition preview").locator('[data-layer-kind="image"] img')).toBeVisible();
  await studio.getByLabel("New layer kind").selectOption("three");
  await studio.getByRole("button", { name: "Add layer" }).click();
  await studio.getByLabel("Layer name").fill("Product pyramid");
  await studio.getByLabel("3D primitive").selectOption("pyramid");
  await studio.getByLabel("3D primary color").fill("#ffff00");
  await studio.getByLabel("3D secondary color").fill("#aa8800");
  await studio.getByLabel("3D depth").fill("1.5");
  await studio.getByLabel("Layer x").fill("0.72");
  await studio.getByLabel("Layer y").fill("0.32");
  await studio.getByLabel("Layer width").fill("0.18");
  await studio.getByLabel("Layer height").fill("0.18");
  await studio.getByLabel("Layer rotate x").fill("12");
  await studio.getByLabel("Layer rotate y").fill("24");
  await studio.getByLabel("Layer perspective").fill("800");
  const threePreview = studio.getByLabel("Deterministic composition preview").locator('[data-layer-kind="three"] img');
  await expect(threePreview).toHaveAttribute("alt", "pyramid primitive");
  await expect(threePreview).toHaveAttribute("src", /^data:image\/svg\+xml/);
  await studio.getByLabel("Selected layer").selectOption("hero_title");
  await studio.getByLabel("Layer private font").selectOption(fontAsset.id);
  await studio.getByLabel("Layer rotation").fill("-8");
  await studio.getByLabel("Keyframe property").selectOption("scale");
  await studio.getByLabel("Keyframe frame").fill("45");
  await studio.getByLabel("Keyframe value").fill("1.4");
  await studio.getByRole("button", { name: "Add or replace keyframe" }).click();
  await studio.getByLabel("enter transition", { exact: true }).selectOption("slide");
  await studio.getByRole("button", { name: "Save composition" }).click();
  await expect(studio.getByText("Composition controls saved.")).toBeVisible();
  await studio.getByRole("button", { name: "Apply" }).click();
  await expect(studio.getByText(/now on the editable timeline/)).toBeVisible();
  const renderResponse = await request(page, owner, "POST", `/api/cut/projects/${project.id}/render`, { aspect: "16:9", captions: false, cleanAudio: false, quality: "draft", resolution: "720p", fps: 24 });
  await expectOk(renderResponse);
  const render = await renderResponse.json();
  await expect.poll(async () => (await (await request(page, owner, "GET", `/api/cut/jobs/${render.id}`)).json()).state, { timeout: 60_000, intervals: [500, 1_000] }).not.toMatch(/queued|running/);
  const renderedJob = await request(page, owner, "GET", `/api/cut/jobs/${render.id}`);
  await expectOk(renderedJob);
  const completedRender = await renderedJob.json();
  expect(completedRender, completedRender.detail).toMatchObject({ state: "done", artifactAssetId: expect.any(String) });
  const renderMedia = await request(page, owner, "GET", `/api/cut/jobs/${render.id}/media`);
  await expectOk(renderMedia);
  const artifact = await page.request.get((await renderMedia.json()).url);
  await expectOk(artifact);
  const renderedPath = `${directory}/composition-motion.mp4`;
  writeFileSync(renderedPath, await artifact.body());
  const brandBounds = (seconds: number) => {
    const pixels = execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-ss", String(seconds), "-i", renderedPath, "-frames:v", "1", "-f", "rawvideo", "-pix_fmt", "rgb24", "pipe:1"], { maxBuffer: 4 * 1024 * 1024 });
    let minimumX = 1280; let maximumX = -1; let minimumY = 720; let maximumY = -1; let count = 0;
    for (let offset = 0; offset + 2 < pixels.length; offset += 3) {
      const red = pixels[offset]; const green = pixels[offset + 1]; const blue = pixels[offset + 2];
      if (blue > 30 && blue > green + 12 && green > red + 10) {
        const x = Math.floor(offset / 3) % 1280;
        const y = Math.floor(Math.floor(offset / 3) / 1280);
        minimumX = Math.min(minimumX, x); maximumX = Math.max(maximumX, x); minimumY = Math.min(minimumY, y); maximumY = Math.max(maximumY, y); count += 1;
      }
    }
    return { minimumX, maximumX, minimumY, maximumY, count };
  };
  const openingTitle = brandBounds(.55);
  const settledTitle = brandBounds(1.1);
  expect(openingTitle.count).toBeGreaterThan(1_000);
  expect(settledTitle.count).toBeGreaterThan(1_000);
  expect(openingTitle.minimumX - settledTitle.minimumX).toBeGreaterThan(120);
  expect(settledTitle.count).toBeGreaterThan(openingTitle.count * 1.05);
  expect(settledTitle.maximumY - settledTitle.minimumY).toBeGreaterThan(180);
  const settledPixels = execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-ss", "1.1", "-i", renderedPath, "-frames:v", "1", "-f", "rawvideo", "-pix_fmt", "rgb24", "pipe:1"], { maxBuffer: 4 * 1024 * 1024 });
  const accentOffset = ((500 * 1280) + 500) * 3;
  expect({ red: settledPixels[accentOffset], green: settledPixels[accentOffset + 1], blue: settledPixels[accentOffset + 2] }).toMatchObject({ red: expect.any(Number), green: expect.any(Number), blue: expect.any(Number) });
  expect(settledPixels[accentOffset]).toBeGreaterThan(settledPixels[accentOffset + 1] + 60);
  expect(settledPixels[accentOffset]).toBeGreaterThan(settledPixels[accentOffset + 2] + 40);
  expect(settledPixels[accentOffset]).toBeLessThan(230);
  let accentMinimumX = 1280; let accentMaximumX = -1; let accentMinimumY = 720; let accentMaximumY = -1;
  const accentRowCounts = new Map<number, number>();
  for (let offset = 0; offset + 2 < settledPixels.length; offset += 3) {
    const red = settledPixels[offset]; const green = settledPixels[offset + 1]; const blue = settledPixels[offset + 2];
    if (red > green + 60 && red > blue + 40) {
      const pixel = Math.floor(offset / 3); const x = pixel % 1280; const y = Math.floor(pixel / 1280);
      accentMinimumX = Math.min(accentMinimumX, x); accentMaximumX = Math.max(accentMaximumX, x); accentMinimumY = Math.min(accentMinimumY, y); accentMaximumY = Math.max(accentMaximumY, y);
      accentRowCounts.set(y, (accentRowCounts.get(y) ?? 0) + 1);
    }
  }
  const widestAccentRow = Math.max(...accentRowCounts.values());
  const middleAccentRow = accentRowCounts.get(Math.round((accentMinimumY + accentMaximumY) / 2)) ?? 0;
  const topAccentRow = accentRowCounts.get(accentMinimumY) ?? 0;
  const bottomAccentRow = accentRowCounts.get(accentMaximumY) ?? 0;
  expect(widestAccentRow).toBeGreaterThan(600);
  expect(middleAccentRow).toBeLessThan(widestAccentRow - 150);
  expect(Math.abs(bottomAccentRow - topAccentRow)).toBeGreaterThan(60);
  const openingPixels = execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-ss", "0.25", "-i", renderedPath, "-frames:v", "1", "-f", "rawvideo", "-pix_fmt", "rgb24", "pipe:1"], { maxBuffer: 4 * 1024 * 1024 });
  const revealCornerOffset = ((350 * 1280) + 400) * 3;
  const revealCenterOffset = ((486 * 1280) + 544) * 3;
  expect(openingPixels[revealCornerOffset]).toBeLessThan(40);
  expect(openingPixels[revealCenterOffset]).toBeGreaterThan(80);
  expect(settledPixels[revealCornerOffset]).toBeGreaterThan(80);
  const wipeLeftOffset = ((470 * 1280) + 90) * 3;
  const wipeRightOffset = ((470 * 1280) + 310) * 3;
  expect(openingPixels[wipeLeftOffset]).toBeLessThan(40);
  expect(openingPixels[wipeRightOffset]).toBeGreaterThan(120);
  expect(settledPixels[wipeLeftOffset]).toBeGreaterThan(120);
  const clockTopOffset = ((410 * 1280) + 1088) * 3;
  const clockBottomOffset = ((530 * 1280) + 1088) * 3;
  expect(openingPixels[clockTopOffset + 1]).toBeGreaterThan(120);
  expect(openingPixels[clockBottomOffset + 1]).toBeLessThan(40);
  expect(settledPixels[clockBottomOffset + 1]).toBeGreaterThan(120);
  const customMaskLeftOffset = ((630 * 1280) + 560) * 3;
  const customMaskRightOffset = ((630 * 1280) + 720) * 3;
  expect(settledPixels[customMaskLeftOffset + 1]).toBeLessThan(100);
  expect(settledPixels[customMaskRightOffset + 1]).toBeGreaterThan(200);
  const vacatedAccentOffset = ((500 * 1280) + 1000) * 3;
  expect(settledPixels[vacatedAccentOffset]).toBeLessThan(80);
  const ruleOffset = ((486 * 1280) + 850) * 3;
  expect(settledPixels[ruleOffset]).toBeGreaterThan(150);
  expect(settledPixels[ruleOffset + 1]).toBeGreaterThan(150);
  expect(settledPixels[ruleOffset + 2]).toBeGreaterThan(150);
  const svgOffset = ((162 * 1280) + 288) * 3;
  expect(settledPixels[svgOffset + 1]).toBeGreaterThan(180);
  expect(settledPixels[svgOffset]).toBeLessThan(60);
  expect(settledPixels[svgOffset + 2]).toBeLessThan(60);
  const imageOffset = ((108 * 1280) + 1024) * 3;
  expect(settledPixels[imageOffset]).toBeGreaterThan(180);
  expect(settledPixels[imageOffset + 1]).toBeLessThan(60);
  expect(settledPixels[imageOffset + 2]).toBeGreaterThan(180);
  let threePixelCount = 0;
  for (let offset = 0; offset + 2 < settledPixels.length; offset += 3) {
    if (settledPixels[offset] > 145 && settledPixels[offset + 1] > 105 && settledPixels[offset + 2] < 80) threePixelCount += 1;
  }
  expect(threePixelCount).toBeGreaterThan(1_000);
  const variantBatch = studio.getByLabel("Composition variant batch");
  await variantBatch.getByLabel("Variant 1 name").fill("Launch · A");
  await variantBatch.getByLabel("Variant 1 Headline").fill("Create once");
  await variantBatch.getByLabel("Variant 2 name").fill("Launch · B");
  await variantBatch.getByLabel("Variant 2 Headline").fill("Publish everywhere");
  await variantBatch.getByLabel("Variant 3 name").fill("Launch · C");
  await variantBatch.getByLabel("Variant 3 Headline").fill("Own the audience");
  await variantBatch.getByRole("button", { name: "Create 3" }).focus();
  await variantBatch.getByRole("button", { name: "Create 3" }).press("Enter");
  await expect(studio.getByText("3 parameterized composition variants created.")).toBeVisible();

  await studio.getByRole("button", { name: /Cinema/ }).click();
  await studio.getByLabel("Production title").fill("World launch");
  await studio.getByLabel("Objective").fill("Create a coherent multi-shot launch film");
  await studio.getByLabel("Audience").fill("Independent creative teams");
  await studio.getByRole("button", { name: "Save brief" }).click();
  await expect(studio.getByText("Production brief saved.")).toBeVisible();
  await studio.getByLabel("Shot name").fill("Hero reveal");
  await studio.getByLabel("Shot prompt").fill("Slow dolly toward the subject as the creative workspace comes alive");
  await studio.getByText(/I control the media\/model rights/).click();
  await studio.getByRole("button", { name: "Add shot" }).click();
  await expect(studio.getByText("Shot added to the production plan.")).toBeVisible();
  await studio.getByRole("button", { name: "Generate Hero reveal" }).click();
  await expect(studio.getByText(/safely staged|Generation submitted/)).toBeVisible();
  await expect(studio.getByText(/provider pending/)).toBeVisible();

  await studio.getByRole("button", { name: /Flows/ }).click();
  await studio.getByRole("button", { name: "Starter campaign flow" }).click();
  await expect(studio.getByText("Reusable generation workflow saved.")).toBeVisible();
  await expect(studio.getByLabel("Workflow name")).toHaveValue("Cinematic campaign pipeline");
  await studio.getByLabel("hero_image prompt").fill("Create a precise launch hero image");
  await studio.getByLabel("New workflow operation").selectOption("video_to_video");
  await studio.getByRole("button", { name: "Node", exact: true }).click();
  const finishingNodeId = await studio.getByLabel("Connection target").inputValue();
  expect(finishingNodeId).toMatch(/^video_to_video_/);
  await expect(studio.getByLabel(`${finishingNodeId} operation`)).toHaveValue("video_to_video");
  await studio.getByLabel("Connection source").selectOption("hero_video");
  await studio.getByLabel("Connection slot").selectOption("source_video");
  await studio.getByRole("button", { name: "Connect nodes" }).click();
  await studio.getByRole("button", { name: "Output", exact: true }).focus();
  await studio.getByRole("button", { name: "Output", exact: true }).press("Enter");
  await studio.getByRole("button", { name: "Save graph" }).focus();
  await studio.getByRole("button", { name: "Save graph" }).press("Enter");
  await expect(studio.getByText("Workflow graph saved.")).toBeVisible();

  const runtimeResponse = await request(page, owner, "GET", `/api/cut/projects/${project.id}/creative-runtime`);
  await expectOk(runtimeResponse);
  const runtime = await runtimeResponse.json();
  const sourceComposition = runtime.compositions.find((composition: { manifest: { metadata: Record<string, unknown> } }) => !composition.manifest.metadata.sourceCompositionId);
  expect(sourceComposition).toMatchObject({ manifest: expect.objectContaining({ parameters: [expect.objectContaining({ key: "headline", defaultValue: "A connected creative system" })], fonts: [expect.objectContaining({ assetId: fontAsset.id })], layers: expect.arrayContaining([expect.objectContaining({ text: "A connected creative system", rotation: -8, dataBindings: { text: "headline" }, style: expect.objectContaining({ fontFamily: expect.stringMatching(/^CreativesOS_/) }), animations: expect.arrayContaining([expect.objectContaining({ property: "scale", keyframes: expect.arrayContaining([expect.objectContaining({ frame: 44, value: 1.4 })]) })]) }), expect.objectContaining({ name: "Project B-roll", kind: "video", assetId: source.id }), expect.objectContaining({ name: "Brand accent", kind: "shape", rotationX: -18, rotationY: 32, perspective: 700, style: expect.objectContaining({ fill: "#f43f5e" }), effects: expect.arrayContaining([expect.objectContaining({ kind: "glow", parameters: expect.objectContaining({ radius: 20 }) }), expect.objectContaining({ kind: "drop_shadow", parameters: expect.objectContaining({ blur: 8 }) })]), animations: expect.arrayContaining([expect.objectContaining({ property: "opacity", keyframes: [expect.objectContaining({ frame: 12, value: .75 })] }), expect.objectContaining({ property: "x", keyframes: [expect.objectContaining({ frame: 30, value: .25 })] }), expect.objectContaining({ property: "scale", keyframes: [expect.objectContaining({ frame: 45, value: 1.4 })] }), expect.objectContaining({ property: "blur", keyframes: [expect.objectContaining({ frame: 20, value: 3 })] }), expect.objectContaining({ property: "brightness", keyframes: [expect.objectContaining({ frame: 20, value: .9 })] }), expect.objectContaining({ property: "saturation", keyframes: [expect.objectContaining({ frame: 20, value: .7 })] })]) }), expect.objectContaining({ name: "Vector rule", kind: "path" })]) }) });
  const persistedLayers = sourceComposition.manifest.layers as Array<{ name: string; effects: Array<{ kind: string; parameters: Record<string, unknown> }> }>;
  expect(persistedLayers.find((layer) => layer.name === "Clock wipe accent")?.effects.map((effect) => effect.kind)).toEqual(["grain", "noise", "vignette", "color_matrix", "chroma_key", "displacement", "motion_blur", "light_leak"]);
  expect(persistedLayers.find((layer) => layer.name === "Custom mask accent")?.effects).toEqual([expect.objectContaining({ kind: "mask", parameters: expect.objectContaining({ maskAssetId: maskAsset.id }) })]);
  const compositionVariants = runtime.compositions.filter((composition: { manifest: { metadata: Record<string, unknown> } }) => composition.manifest.metadata.sourceCompositionId === sourceComposition.id);
  expect(compositionVariants).toHaveLength(3);
  expect(compositionVariants.map((composition: { manifest: { layers: Array<{ id: string; text?: string }> } }) => composition.manifest.layers.find((layer) => layer.id === "hero_title")?.text).sort()).toEqual(["Create once", "Own the audience", "Publish everywhere"]);
  const repeatedBatch = await request(page, owner, "POST", `/api/cut/projects/${project.id}/compositions/${sourceComposition.id}/variants`, { idempotencyKey: compositionVariants[0].manifest.metadata.variantBatchId, variants: [{ name: "Launch · A", parameterValues: { headline: "Create once" } }, { name: "Launch · B", parameterValues: { headline: "Publish everywhere" } }, { name: "Launch · C", parameterValues: { headline: "Own the audience" } }] });
  await expectOk(repeatedBatch);
  expect((await repeatedBatch.json()).variants.map((composition: { id: string }) => composition.id).sort()).toEqual(compositionVariants.map((composition: { id: string }) => composition.id).sort());
  expect(runtime).toMatchObject({ plan: { brief: expect.objectContaining({ title: "World launch" }) }, shots: [expect.objectContaining({ spec: expect.objectContaining({ name: "Hero reveal", safety: expect.objectContaining({ rightsConfirmed: true }) }) })], jobs: [expect.objectContaining({ state: "provider_pending" })], workflows: [expect.objectContaining({ workflow: expect.objectContaining({ name: "Cinematic campaign pipeline", outputs: expect.arrayContaining([expect.objectContaining({ label: "Output 3" })]), nodes: expect.arrayContaining([expect.objectContaining({ prompt: "Create a precise launch hero image" }), expect.objectContaining({ operation: "video_to_video", inputs: [expect.objectContaining({ slot: "source_video", sourceNodeId: "hero_video" })] })]) }) })] });

  await studio.getByRole("button", { name: /Cinema/ }).focus();
  await studio.getByRole("button", { name: /Cinema/ }).press("Enter");
  await expect(studio.getByLabel("Variant review for Hero reveal")).toBeVisible();
  await expect(studio.getByLabel("Candidate video for Hero reveal")).toHaveValue(source.id);
  await studio.getByRole("button", { name: "Add candidate for Hero reveal" }).click();
  await expect(studio.getByText("The project video is ready for shot review with its source lineage retained.")).toBeVisible();
  await expect(studio.getByLabel("Preview source.mp4")).toBeVisible();
  await studio.getByRole("button", { name: "Select source.mp4" }).click();
  await expect(studio.getByText("Variant selected. You can now hand it directly to the editable timeline.")).toBeVisible();
  await studio.getByRole("button", { name: "Add source.mp4 to timeline" }).click();
  await expect(studio.getByText("Selected variant added to the editable timeline without export or re-upload.")).toBeVisible();
  const handoffRuntimeResponse = await request(page, owner, "GET", `/api/cut/projects/${project.id}/creative-runtime`);
  await expectOk(handoffRuntimeResponse);
  const handoffRuntime = await handoffRuntimeResponse.json();
  const selectedVariant = handoffRuntime.variants.find((variant: { shotId: string; status: string }) => variant.shotId === runtime.shots[0].id && variant.status === "selected");
  expect(selectedVariant).toMatchObject({ assetId: source.id, provider: "project_media", model: "manual_import", provenance: expect.objectContaining({ source: "project_media" }) });
  const handedOffProjectResponse = await request(page, owner, "GET", `/api/cut/projects/${project.id}`);
  await expectOk(handedOffProjectResponse);
  const handedOffProject = await handedOffProjectResponse.json();
  expect(handedOffProject.edl.clips).toEqual(expect.arrayContaining([expect.objectContaining({ assetId: source.id, sourceVariantId: selectedVariant.id, track: "v1", timelineStart: expect.any(Number) })]));
  await studio.getByRole("button", { name: "Add source.mp4 to timeline" }).click();
  await expect(studio.getByText("This selected variant is already on the editable timeline.")).toBeVisible();

  const foreignUpload = await page.request.post("/api/assets/upload-proxy", { headers: { "x-creativesos-demo-user": String(peer) }, multipart: { kind: "video", visibility: "private", video: { name: "foreign.mp4", mimeType: "video/mp4", buffer: readFileSync(sourcePath) } } });
  await expectOk(foreignUpload);
  const foreignAsset = (await foreignUpload.json()).asset;
  const foreignVariant = await request(page, owner, "POST", `/api/cut/projects/${project.id}/shots/${runtime.shots[0].id}/variants/import`, { assetId: foreignAsset.id, label: "Foreign candidate" });
  expect(foreignVariant.status()).toBe(409);
  expect(await foreignVariant.json()).toMatchObject({ message: "Only ready private project video may enter variant review" });
  const foreignGeneration = await request(page, owner, "POST", `/api/cut/projects/${project.id}/shots/${runtime.shots[0].id}/generations`, { ...runtime.jobs[0].request, inputs: [{ slot: "reference_video", assetIds: [foreignAsset.id], required: true }], idempotencyKey: `foreign.${crypto.randomUUID()}` });
  expect(foreignGeneration.status()).toBe(400);
  expect(await foreignGeneration.json()).toMatchObject({ message: "Every referenced asset must be a ready private asset in this business" });
  const foreignWorkflow = structuredClone(runtime.workflows[0].workflow);
  foreignWorkflow.nodes[0].inputs = [{ slot: "reference_video", assetIds: [foreignAsset.id] }];
  const foreignWorkflowUpdate = await request(page, owner, "PUT", `/api/cut/projects/${project.id}/generative-workflows/${runtime.workflows[0].id}`, { workflow: foreignWorkflow }, { "If-Match": String(runtime.workflows[0].revision) });
  expect(foreignWorkflowUpdate.status()).toBe(400);

  await expectOk(await request(page, owner, "POST", `/api/cut/projects/${project.id}/collaborators`, { username: peerUsername, role: "reviewer" }));
  await expectOk(await request(page, peer, "GET", `/api/cut/projects/${project.id}/creative-runtime`));
  const reviewerMutation = await request(page, peer, "POST", `/api/cut/projects/${project.id}/generative-workflows`, { workflow: runtime.workflows[0].workflow });
  expect(reviewerMutation.status()).toBe(403);
});
