import { expect, test } from "@playwright/test";
test.setTimeout(120_000);

test("DesignStudio saves, versions, reviews, resizes, exports, and distributes governed graphics", async ({ page }, testInfo) => {
  const stamp = `${testInfo.project.name}-${Date.now()}`;
  const createdResponse = await page.request.post("/api/design", { data: { name: `Launch ${stamp}`, kind: "thumbnail", width: 1280, height: 720, brandKitId: null } }); expect(createdResponse.status()).toBe(201); const project = await createdResponse.json() as { id: string; revision: number; document: { pages: Array<{ id: string; elements: unknown[] }> } };
  const document = structuredClone(project.document); document.pages[0].elements.push({ id: "proof", type: "shape", shape: "ellipse", x: 900, y: 400, width: 220, height: 220, rotation: 0, opacity: 0.9, locked: true, zIndex: 9, fill: "#1d9bf0", stroke: "#ffffff", strokeWidth: 4, radius: 0 });
  const saved = await page.request.patch(`/api/design/${project.id}`, { data: { revision: project.revision, document } }); expect(saved.status()).toBe(200); const savedProject = await saved.json() as { revision: number }; expect(savedProject.revision).toBe(project.revision + 1);
  const stale = await page.request.patch(`/api/design/${project.id}`, { data: { revision: project.revision, document } }); expect(stale.status()).toBe(409);
  const template = await page.request.post(`/api/design/${project.id}/templates`, { data: { name: `Locked ${stamp}` } }); expect(template.status()).toBe(201); expect((await template.json()).lockedElementIds).toContain("proof");
  const variant = await page.request.post(`/api/design/${project.id}/resize`, { data: { name: `Square ${stamp}`, width: 1080, height: 1080, mode: "fit" } }); expect(variant.status()).toBe(201); expect((await variant.json()).sourceProjectId).toBe(project.id);
  const versionResponse = await page.request.post(`/api/design/${project.id}/versions`, { data: { label: "Client review" } }); expect(versionResponse.status()).toBe(201); const version = await versionResponse.json() as { id: string; revision: number }; expect(version.revision).toBe(savedProject.revision);
  const reviewResponse = await page.request.post(`/api/design/versions/${version.id}/review`, { data: { label: "Launch creative", days: 7 } }); expect(reviewResponse.status()).toBe(201); const review = await reviewResponse.json() as { reviewUrl: string }; const token = review.reviewUrl.split("/").at(-1)!;
  const publicReview = await page.request.get(`/api/design/reviews/${token}`); expect(publicReview.status()).toBe(200); expect((await publicReview.json()).version.document.pages[0].elements).toHaveLength(3);
  const preview = await page.request.get(`/api/design/reviews/${token}/preview.svg?pageId=page-1`); expect(preview.status()).toBe(200); expect(await preview.text()).toContain("Make the idea impossible to ignore");
  expect((await page.request.post(`/api/design/reviews/${token}/comments`, { data: { reviewerName: "Reviewer", body: "Increase contrast", pageId: "page-1", x: 0.4, y: 0.5 } })).status()).toBe(201);
  expect((await page.request.post(`/api/design/reviews/${token}/decision`, { data: { reviewerName: "Reviewer", decision: "approved", note: "Ready" } })).status()).toBe(201);
  for (const format of ["svg", "png", "jpeg", "webp"]) { const exported = await page.request.post(`/api/design/${project.id}/export`, { data: { format, pageId: "page-1", visibility: "private", quality: 90, scale: format === "svg" ? 1 : 0.5 } }); expect(exported.status()).toBe(201); const payload = await exported.json(); expect(payload.asset.mimeType).toContain(format === "jpeg" ? "jpeg" : format); if (format === "png") { const distribution = await page.request.post(`/api/design/${project.id}/distribution`, { data: { assetId: payload.asset.id, content: "Launch", platforms: ["creativesos"], scheduledFor: new Date(Date.now() + 60_000).toISOString() } }); expect(distribution.status()).toBe(201); expect((await distribution.json()).assetIds).toContain(payload.asset.id); } }
  expect((await page.request.post(`/api/design/${project.id}/collaborators`, { data: { userId: testInfo.project.name === "mobile-chromium" ? 2 : 1, role: "editor" } })).status()).toBe(201);
  await page.goto("/business/design"); await expect(page.getByRole("heading", { name: "DesignStudio" })).toBeVisible(); await expect(page.getByText(`Launch ${stamp}`)).toBeVisible(); await page.getByText(`Launch ${stamp}`).click(); await expect(page.getByLabel("Design canvas")).toBeVisible(); await expect(page.getByRole("button", { name: "Export" })).toBeVisible();
});
