import { expect, test } from "@playwright/test";
test.setTimeout(120_000);
test("Sponsorship Studio carries proof, proposal, signatures, milestones, invoice state, and performance", async ({ page }, testInfo) => {
  const stamp = `${testInfo.project.name}-${Date.now()}`; const rights = { channels: ["youtube","instagram"], territories: ["worldwide"], durationDays: 90, paidMedia: false, whitelisting: false, exclusivityCategory: null, exclusivityDays: 0 };
  expect((await page.request.post("/api/sponsorship/media-kits", { data: { name: `Media kit ${stamp}`, headline: "Owned audience proof", bio: "Qualified", audienceProof: { subscribers: 1000 }, caseStudies: [{ title: "Launch" }], assetIds: [] } })).status()).toBe(201);
  expect((await page.request.post("/api/sponsorship/rate-cards", { data: { name: `Rates ${stamp}`, currency: "usd", items: [{ id: "video", name: "Integrated video", description: "60 seconds", priceCents: 250000, unit: "video" }] } })).status()).toBe(201);
  const dealResponse = await page.request.post("/api/sponsorship/deals", { data: { brandName: `Brand ${stamp}`, contactId: null, campaignId: null, title: `Launch ${stamp}`, description: "Integrated creator campaign", currency: "usd", proposedValueCents: 250000, disclosure: "#ad", usageRights: rights, renewalAt: null } }); expect(dealResponse.status()).toBe(201); const deal = await dealResponse.json() as { id: string };
  const proposalResponse = await page.request.post(`/api/sponsorship/deals/${deal.id}/proposals`, { data: { summary: "One integrated launch campaign", valueCents: 250000, validUntil: new Date(Date.now()+7*86400000).toISOString(), deliverables: [{ id: "video", title: "Integrated video", channel: "youtube", quantity: 1, dueAt: null, requirements: "FTC disclosure", distributionJobId: null }], paymentTerms: "50% on signature, 50% on approval", cancellationTerms: "Earned work remains payable", usageRights: rights } }); expect(proposalResponse.status()).toBe(201);
  const portalResponse = await page.request.post(`/api/sponsorship/deals/${deal.id}/portal`, { data: { stakeholderName: "Brand Reviewer", stakeholderEmail: `${stamp}@example.com` } }); expect(portalResponse.status()).toBe(201); const portalUrl = (await portalResponse.json()).portalUrl as string; const token = portalUrl.split("/").at(-1)!;
  const publicDeal = await page.request.get(`/api/public/sponsorship/${token}`); expect(publicDeal.status()).toBe(200); expect((await publicDeal.json()).proposal.status).toBe("sent");
  expect((await page.request.post(`/api/public/sponsorship/${token}/proposal`, { data: { decision: "accepted" } })).status()).toBe(200);
  expect((await page.request.post(`/api/sponsorship/deals/${deal.id}/sign`, { data: { name: "Creator Owner" } })).status()).toBe(200);
  const brandSign = await page.request.post(`/api/public/sponsorship/${token}/sign`, { data: { name: "Brand Reviewer" } }); expect(brandSign.status()).toBe(200); expect((await brandSign.json()).status).toBe("executed");
  const milestoneResponse = await page.request.post(`/api/sponsorship/deals/${deal.id}/milestones`, { data: { name: "Creative approval", description: "Approved deliverable", dueAt: null, amountCents: 250000 } }); expect(milestoneResponse.status()).toBe(201); const milestone = await milestoneResponse.json() as { id: string };
  expect((await page.request.patch(`/api/sponsorship/milestones/${milestone.id}`, { data: { status: "approved" } })).status()).toBe(200);
  const invoice = await page.request.post(`/api/sponsorship/deals/${deal.id}/invoices`, { data: { milestoneId: milestone.id, dueAt: new Date(Date.now()+30*86400000).toISOString() } }); expect(invoice.status()).toBe(201); expect((await invoice.json()).providerStatus).toBe("provider_pending");
  expect((await page.request.post(`/api/sponsorship/deals/${deal.id}/performance`, { data: { source: "manual_qualification", metrics: { impressions: 10000, clicks: 450, conversions: 25 } } })).status()).toBe(201);
  const prematurePaid = await page.request.patch(`/api/sponsorship/deals/${deal.id}/stage`, { data: { stage: "paid" } }); expect(prematurePaid.status()).toBe(409);
  const detail = await page.request.get(`/api/sponsorship/deals/${deal.id}`); expect(detail.status()).toBe(200); const detailData = await detail.json(); expect(detailData.contract.status).toBe("executed"); expect(detailData.invoices).toHaveLength(1); expect(detailData.performance[0].metrics.conversions).toBe(25);
  await page.goto("/business/sponsorship");
  await expect(page.getByRole("heading", { name: "Sponsorship Studio" })).toBeVisible();
  await page.getByRole("button", { name: new RegExp(`Brand ${stamp}`) }).click();
  await expect(page.getByRole("heading", { name: `Launch ${stamp}` })).toBeVisible();
  await expect(page.getByText("executed", { exact: true })).toBeVisible();
  await expect(page.getByText(/provider attribution can enrich/i)).toBeVisible();
  await page.goto(`/sponsorship/portal/${token}`);
  await expect(page.getByRole("heading", { name: `Launch ${stamp}` })).toBeVisible();
  await expect(page.getByText("Secure sponsorship workspace")).toBeVisible();
  await expect(page.getByText(/conversions: 25/i)).toBeVisible();
});
