import { z } from "zod";

export const createPodcastShowSchema = z.object({
  title: z.string().trim().min(1).max(200), description: z.string().trim().max(10_000).default(""), author: z.string().trim().min(1).max(200), ownerEmail: z.string().trim().email().max(320).transform((value) => value.toLowerCase()), language: z.string().trim().regex(/^[a-z]{2,3}(-[A-Z]{2})?$/).default("en"), category: z.string().trim().min(1).max(120).default("Society & Culture"), explicit: z.boolean().default(false), artworkAssetId: z.string().uuid().nullable().default(null), websiteUrl: z.string().url().max(500).nullable().default(null), copyright: z.string().trim().max(300).default(""), access: z.enum(["public", "members", "private"]).default("public"), entitlementProductId: z.number().int().positive().nullable().default(null),
}).strict().refine((show) => show.access === "public" || show.entitlementProductId !== null, "Member and private shows require an entitlement product");

export const createPodcastSeasonSchema = z.object({ number: z.number().int().positive().max(10_000), title: z.string().trim().min(1).max(200), description: z.string().trim().max(5_000).default(""), artworkAssetId: z.string().uuid().nullable().default(null) }).strict();

const chapterSchema = z.object({ startSeconds: z.number().min(0), title: z.string().trim().min(1).max(200), url: z.string().url().max(500).optional() }).strict();
const sponsorSchema = z.object({ startSeconds: z.number().min(0), endSeconds: z.number().positive(), sponsor: z.string().trim().min(1).max(200), disclosure: z.string().trim().min(1).max(500) }).strict().refine((marker) => marker.endSeconds > marker.startSeconds, "Sponsor marker must end after it starts");
export const createPodcastEpisodeSchema = z.object({
  seasonId: z.string().uuid().nullable().default(null), title: z.string().trim().min(1).max(240), description: z.string().trim().max(20_000).default(""), episodeType: z.enum(["full", "trailer", "bonus"]).default("full"), episodeNumber: z.number().int().positive().nullable().default(null), mediaAssetId: z.string().uuid(), videoAssetId: z.string().uuid().nullable().default(null), artworkAssetId: z.string().uuid().nullable().default(null), chapters: z.array(chapterSchema).max(500).default([]).transform((chapters) => [...chapters].sort((a, b) => a.startSeconds - b.startSeconds)), sponsorshipMarkers: z.array(sponsorSchema).max(100).default([]), explicit: z.boolean().default(false), access: z.enum(["show_default", "public", "members", "private"]).default("show_default"), durationSeconds: z.number().int().positive().nullable().default(null), scheduledAt: z.coerce.date().nullable().default(null),
}).strict().refine((episode) => episode.chapters.every((chapter, index) => index === 0 || chapter.startSeconds > episode.chapters[index - 1].startSeconds), "Chapter times must be unique");

export const podcastPollSchema = z.object({ question: z.string().trim().min(1).max(500), options: z.array(z.object({ id: z.string().trim().regex(/^[a-z0-9_-]{1,40}$/), label: z.string().trim().min(1).max(200) }).strict()).min(2).max(10), closesAt: z.coerce.date().nullable().default(null) }).strict().refine((poll) => new Set(poll.options.map((option) => option.id)).size === poll.options.length, "Poll option IDs must be unique");
