import { z } from "zod";
const money = z.number().int().min(0).max(1_000_000_000);
export const sponsorshipUsageRightsSchema = z.object({ channels: z.array(z.string().min(1).max(80)).max(30), territories: z.array(z.string().min(1).max(80)).max(50).default(["worldwide"]), durationDays: z.number().int().positive().max(3650), paidMedia: z.boolean().default(false), whitelisting: z.boolean().default(false), exclusivityCategory: z.string().max(160).nullable().default(null), exclusivityDays: z.number().int().min(0).max(3650).default(0) }).strict();
export type SponsorshipUsageRights = z.infer<typeof sponsorshipUsageRightsSchema>;
export const createSponsorDealSchema = z.object({ brandName: z.string().trim().min(1).max(200), contactId: z.number().int().positive().nullable().default(null), campaignId: z.string().uuid().nullable().default(null), title: z.string().trim().min(1).max(240), description: z.string().trim().max(10_000).default(""), currency: z.string().regex(/^[a-z]{3}$/).default("usd"), proposedValueCents: money, disclosure: z.string().trim().max(1_000).default("#ad"), usageRights: sponsorshipUsageRightsSchema, renewalAt: z.coerce.date().nullable().default(null) }).strict();
export const sponsorshipDeliverableSchema = z.object({ id: z.string().regex(/^[a-zA-Z0-9_-]{1,80}$/), title: z.string().trim().min(1).max(240), channel: z.string().trim().min(1).max(100), quantity: z.number().int().positive().max(1000), dueAt: z.coerce.date().nullable().default(null), requirements: z.string().max(5_000).default(""), distributionJobId: z.string().uuid().nullable().default(null) }).strict();
export type SponsorshipDeliverable = z.infer<typeof sponsorshipDeliverableSchema>;
export const createSponsorshipProposalSchema = z.object({ summary: z.string().trim().min(1).max(10_000), valueCents: money, validUntil: z.coerce.date(), deliverables: z.array(sponsorshipDeliverableSchema).min(1).max(100), paymentTerms: z.string().trim().min(1).max(2_000), cancellationTerms: z.string().trim().max(2_000).default(""), usageRights: sponsorshipUsageRightsSchema }).strict();
export const sponsorshipMilestoneSchema = z.object({ name: z.string().trim().min(1).max(200), description: z.string().max(2_000).default(""), dueAt: z.coerce.date().nullable().default(null), amountCents: money }).strict();
